// packages/vue/src/pages/Badge.vue
<script lang="ts" setup>
import { ChevronDown } from "lucide-vue-next";
import { Badge } from "@/components/ui/badge";
</script>

<template>
  <div class="flex flex-col gap-20">
    <div class="grid grid-cols-2">
      <div
        class="justify-center items-center flex gap-2 border-b border-e border-foreground/10 p-5 flex-wrap"
      >
        <Badge variant="primary">12%</Badge>
        <Badge variant="secondary">12%</Badge>
        <Badge variant="success">12%</Badge>
        <Badge variant="danger">12%</Badge>
        <Badge variant="pending">12%</Badge>
        <Badge variant="warning">12%</Badge>
      </div>
      <div
        class="justify-center items-center flex gap-2 border-b border-e border-foreground/10 p-5 flex-wrap"
      >
        <Badge variant="primary"> 12% <ChevronDown /> </Badge>
        <Badge variant="secondary"> 12% <ChevronDown /> </Badge>
        <Badge variant="success"> 12% <ChevronDown /> </Badge>
        <Badge variant="danger"> 12% <ChevronDown /> </Badge>
        <Badge variant="pending"> 12% <ChevronDown /> </Badge>
        <Badge variant="warning"> 12% <ChevronDown /> </Badge>
      </div>
      <div
        class="justify-center items-center flex gap-2 border-b border-e border-foreground/10 p-5 flex-wrap"
      >
        <Badge look="outline" variant="primary"> 12% </Badge>
        <Badge look="outline" variant="secondary"> 12% </Badge>
        <Badge look="outline" variant="success"> 12% </Badge>
        <Badge look="outline" variant="danger"> 12% </Badge>
        <Badge look="outline" variant="pending"> 12% </Badge>
        <Badge look="outline" variant="warning"> 12% </Badge>
      </div>
      <div
        class="justify-center items-center flex gap-2 border-b border-e border-foreground/10 p-5 flex-wrap"
      >
        <Badge look="outline" variant="primary"> 12% <ChevronDown /> </Badge>
        <Badge look="outline" variant="secondary"> 12% <ChevronDown /> </Badge>
        <Badge look="outline" variant="success"> 12% <ChevronDown /> </Badge>
        <Badge look="outline" variant="danger"> 12% <ChevronDown /> </Badge>
        <Badge look="outline" variant="pending"> 12% <ChevronDown /> </Badge>
        <Badge look="outline" variant="warning"> 12% <ChevronDown /> </Badge>
      </div>
      <div
        class="justify-center items-center flex gap-2 border-b border-e border-foreground/10 p-5 flex-wrap"
      >
        <Badge look="filled" variant="primary"> 12% </Badge>
        <Badge look="filled" variant="secondary"> 12% </Badge>
        <Badge look="filled" variant="success"> 12% </Badge>
        <Badge look="filled" variant="danger"> 12% </Badge>
        <Badge look="filled" variant="pending"> 12% </Badge>
        <Badge look="filled" variant="warning"> 12% </Badge>
      </div>
      <div
        class="justify-center items-center flex gap-2 border-b border-e border-foreground/10 p-5 flex-wrap"
      >
        <Badge look="filled" variant="primary"> 12% <ChevronDown /> </Badge>
        <Badge look="filled" variant="secondary"> 12% <ChevronDown /> </Badge>
        <Badge look="filled" variant="success"> 12% <ChevronDown /> </Badge>
        <Badge look="filled" variant="danger"> 12% <ChevronDown /> </Badge>
        <Badge look="filled" variant="pending"> 12% <ChevronDown /> </Badge>
        <Badge look="filled" variant="warning"> 12% <ChevronDown /> </Badge>
      </div>
    </div>
  </div>
</template>

// packages/svelte/src/pages/Badge.svelte
<script lang="ts">
  import { Badge } from "@/components/ui/badge";
</script>

<div class="flex flex-col gap-6">
  <div class="flex flex-wrap gap-2">
    <Badge variant="primary">Primary</Badge>
    <Badge variant="secondary">Secondary</Badge>
    <Badge variant="success">Success</Badge>
    <Badge variant="danger">Danger</Badge>
    <Badge variant="pending">Pending</Badge>
    <Badge variant="warning">Warning</Badge>
  </div>
  <div class="flex flex-wrap gap-2">
    <Badge look="outline" variant="primary">Outline Primary</Badge>
    <Badge look="outline" variant="secondary">Outline Secondary</Badge>
    <Badge look="outline" variant="success">Outline Success</Badge>
    <Badge look="outline" variant="danger">Outline Danger</Badge>
  </div>
</div>
