// packages/react/src/pages/textarea.tsx
import { Textarea } from "@/components/ui/textarea";

function Main() {
  return (
    <div className="flex flex-col gap-20">
      <div className="grid grid-cols-2">
        <div className="justify-center items-center flex gap-2 border-b border-e border-foreground/10 p-5 flex-wrap">
          <Textarea placeholder="Type your message here." />
        </div>
      </div>
    </div>
  );
}

export default Main;

// packages/svelte/src/pages/Textarea.svelte
<script lang="ts">
  import { Textarea } from "@/components/ui/textarea";
  import { Label } from "@/components/ui/label";
</script>

<div class="flex flex-col gap-6 max-w-md">
  <div class="flex flex-col gap-2">
    <Label>Message</Label>
    <Textarea placeholder="Enter your message..." />
  </div>
  <div class="flex flex-col gap-2">
    <Label>Disabled</Label>
    <Textarea disabled placeholder="This textarea is disabled" />
  </div>
</div>
