// packages/react/src/pages/react/radio-group.tsx
import {
  RadioGroupRoot,
  RadioGroupItem,
} from "@/components/ui/radio-group";
import {
  Preview,
  SectionTitle,
  SectionContent,
  InstallPackage,
  PreviewCode,
} from "@/components/docs";

function Main() {
  const frameworks = ["React", "Solid", "Vue", "Svelte"];

  return (
    <>
      <div id="preview" className="-mt-20">
        <Preview>
          {() => ({
            preview: (
              <>
                <RadioGroupRoot defaultValue="React" label="Framework">
                  {frameworks.map((framework) => (
                    <RadioGroupItem key={framework} value={framework}>
                      {framework}
                    </RadioGroupItem>
                  ))}
                </RadioGroupRoot>
              </>
            ),
            code: (
              <PreviewCode>
                {`
const frameworks = ["React", "Solid", "Vue", "Svelte"];
                    
<RadioGroupRoot defaultValue="React" label="Framework">
  {frameworks.map((framework) => (
    <RadioGroupItem key={framework} value={framework}>
      {framework}
    </RadioGroupItem>
  ))}
</RadioGroupRoot>
                        `}
              </PreviewCode>
            ),
          })}
        </Preview>
      </div>
      <div id="installation">
        <SectionTitle>Installation</SectionTitle>
        <SectionContent>Install the following dependencies:</SectionContent>
        <InstallPackage>add @zag-js/react @zag-js/radio-group</InstallPackage>
        <SectionContent>
          Copy and paste the following code into your project.
        </SectionContent>
        <PreviewCode title="components/ui/radio-group/index.tsx">
          {`
import { cn } from "@midoneui/core/utils/cn";
import {
  radioGroupRoot,
  radioGroupLabel,
  radioGroupIndicator,
  radioGroupItem,
  radioGroupItemText,
  radioGroupItemControl,
  radioGroupItemHiddenInput,
} from "@midoneui/core/styles/radio-group.styles";
import { label } from "@midoneui/core/styles/label.styles";
import { createContext, useContext, useId } from "react";
import { Dot } from "lucide-react";
import * as radio from "@zag-js/radio-group";
import { useMachine, normalizeProps } from "@zag-js/react";
import type { Api, Props, ItemProps } from "@zag-js/radio-group";
import { Slot } from "@/components/ui/slot";

const ApiContext = createContext<Api | null>(null);
const ItemContext = createContext<ItemProps | undefined>(undefined);

export function RadioGroupRoot({
  children,
  className,
  asChild = false,
  label,
  ...props
}: React.ComponentProps<"div"> & Partial<Props> & { asChild?: boolean; label?: string }) {
  const service = useMachine(radio.machine, {
    ...props,
    id: useId(),
  });

  const api = radio.connect(service, normalizeProps);

  return (
    <ApiContext.Provider value={api}>
      <Slot
        className={cn(radioGroupRoot, className)}
        {...api?.getRootProps()}
        {...props}
      >
        {asChild ? (
          children
        ) : (
          <div>
            {label && <RadioGroupLabel>{label}</RadioGroupLabel>}
            {children}
            <RadioGroupIndicator>
              <Dot />
            </RadioGroupIndicator>
          </div>
        )}
      </Slot>
    </ApiContext.Provider>
  );
}

export function RadioGroupLabel({
  children,
  className,
  asChild = false,
  ...props
}: React.ComponentProps<"span"> & { asChild?: boolean }) {
  const api = useContext(ApiContext);

  return (
    <Slot
      className={cn([label, radioGroupLabel, className])}
      {...api?.getLabelProps()}
      {...props}
    >
      {asChild ? children : <span>{children}</span>}
    </Slot>
  );
}

export function RadioGroupIndicator({
  children,
  className,
  asChild = false,
  ...props
}: React.ComponentProps<"div"> & { asChild?: boolean }) {
  const api = useContext(ApiContext);

  return (
    <Slot
      className={cn(radioGroupIndicator, className)}
      {...api?.getIndicatorProps()}
      {...props}
    >
      {asChild ? children : <div>{children}</div>}
    </Slot>
  );
}

export function RadioGroupItem({
  children,
  className,
  asChild = false,
  ...props
}: React.ComponentProps<"label"> & ItemProps & { asChild?: boolean }) {
  const api = useContext(ApiContext);

  return (
    <ItemContext.Provider value={props}>
      <Slot
        className={cn(radioGroupItem, className)}
        {...api?.getItemProps(props)}
        {...props}
      >
        {asChild ? (
          children
        ) : (
          <label>
            <RadioGroupItemControl />
            {children && <RadioGroupItemText>{children}</RadioGroupItemText>}
            <RadioGroupItemHiddenInput />
          </label>
        )}
      </Slot>
    </ItemContext.Provider>
  );
}

export function RadioGroupItemText({
  children,
  className,
  asChild = false,
  ...props
}: React.ComponentProps<"span"> & { asChild?: boolean }) {
  const api = useContext(ApiContext);
  const itemProps = useContext(ItemContext);

  return (
    <Slot
      className={cn(radioGroupItemText, className)}
      {...api?.getItemTextProps(itemProps!)}
      {...props}
    >
      {asChild ? children : <span>{children}</span>}
    </Slot>
  );
}

export function RadioGroupItemControl({
  children,
  className,
  asChild = false,
  ...props
}: React.ComponentProps<"div"> & { asChild?: boolean }) {
  const api = useContext(ApiContext);
  const itemProps = useContext(ItemContext);

  return (
    <Slot
      className={cn(radioGroupItemControl, className)}
      {...api?.getItemControlProps(itemProps!)}
      {...props}
    >
      {asChild ? children : <div>{children}</div>}
    </Slot>
  );
}

export function RadioGroupItemHiddenInput({
  children,
  className,
  ...props
}: React.ComponentProps<"input">) {
  const api = useContext(ApiContext);
  const itemProps = useContext(ItemContext);

  return (
    <input
      className={cn(radioGroupItemHiddenInput, className)}
      {...api?.getItemHiddenInputProps(itemProps!)}
      {...props}
    />
  );
}
              `}
        </PreviewCode>
        <SectionContent>
          Update the import paths to match your project setup.
        </SectionContent>
      </div>
      <div id="usage">
        <SectionTitle>Usage</SectionTitle>
        <PreviewCode>
          {`
import {
  RadioGroupRoot,
  RadioGroupItem,
} from "@/components/ui/radio-group";
              `}
        </PreviewCode>
        <PreviewCode>
          {`
<RadioGroupRoot defaultValue="React" label="Framework">
  {frameworks.map((framework) => (
    <RadioGroupItem key={framework} value={framework}>
      {framework}
    </RadioGroupItem>
  ))}
</RadioGroupRoot>
              `}
        </PreviewCode>
      </div>
    </>
  );
}

export default Main;

// packages/docs/src/pages/vue/radio-group.tsx
import {
  RadioGroupRoot,
  RadioGroupLabel,
  RadioGroupItem,
  RadioGroupItemText,
  RadioGroupItemControl,
} from "@/components/ui/radio-group";
import {
  Preview,
  SectionTitle,
  SectionContent,
  InstallPackage,
  PreviewCode,
} from "@/components/docs";

function Main() {
  const frameworks = ["React", "Solid", "Vue", "Svelte"];

  return (
    <>
      <div id="preview" className="-mt-20">
        <Preview>
          {() => ({
            preview: (
              <>
                <RadioGroupRoot defaultValue="React">
                  <RadioGroupLabel>Framework</RadioGroupLabel>
                  {frameworks.map((framework) => (
                    <RadioGroupItem key={framework} value={framework}>
                      <RadioGroupItemControl />
                      <RadioGroupItemText>{framework}</RadioGroupItemText>
                    </RadioGroupItem>
                  ))}
                </RadioGroupRoot>
              </>
            ),
            code: (
              <PreviewCode>
                {`
const frameworks = ["React", "Solid", "Vue", "Svelte"];

<RadioGroupRoot defaultValue="React">
  <RadioGroupLabel>Framework</RadioGroupLabel>
  <RadioGroupItem
    v-for="framework in frameworks"
    :key="framework"
    :value="framework"
  >
    <RadioGroupItemControl />
    <RadioGroupItemText>{{ framework }}</RadioGroupItemText>
  </RadioGroupItem>
</RadioGroupRoot>
                        `}
              </PreviewCode>
            ),
          })}
        </Preview>
      </div>
      <div id="installation">
        <SectionTitle>Installation</SectionTitle>
        <SectionContent>Install the following dependencies:</SectionContent>
        <InstallPackage>add @zag-js/vue @zag-js/radio-group</InstallPackage>
        <SectionContent>
          Copy and paste the following code into your project.
        </SectionContent>
        <PreviewCode title="components/ui/radio-group/RadioGroupRoot.vue">
          {`
<script lang="ts" setup>
import * as radioGroup from "@zag-js/radio-group";
import type { Props } from "@zag-js/radio-group";
import { Slot } from "@/components/ui/slot";
import { cn } from "@midoneui/core/utils/cn";
import { normalizeProps, useMachine } from "@zag-js/vue";
import { computed, provide } from "vue";
import { radioGroupRoot } from "@midoneui/core/styles/radio-group.styles";
import { Dot } from "lucide-vue-next";
import { RadioGroupIndicator } from ".";

const {
  class: className,
  asChild = false,
  ...props
} = defineProps<Partial<Props> & { class?: string; asChild?: boolean }>();

const service = useMachine(radioGroup.machine, {
  ...props,
  id: crypto.randomUUID(),
});
const api = computed(() => radioGroup.connect(service, normalizeProps));

provide("radioGroupApi", api);
</script>

<template>
  <Slot
    :class="cn(radioGroupRoot, className)"
    v-bind="{ ...props, ...$attrs, ...api.getRootProps() }"
  >
    <slot v-if="asChild" />
    <div v-else>
      <slot />
      <RadioGroupIndicator>
        <Dot />
      </RadioGroupIndicator>
    </div>
  </Slot>
</template>
            `}
        </PreviewCode>
        <PreviewCode title="components/ui/radio-group/RadioGroupLabel.vue">
          {`
<script lang="ts" setup>
import { cn } from "@midoneui/core/utils/cn";
import { radioGroupLabel } from "@midoneui/core/styles/radio-group.styles";
import { label } from "@midoneui/core/styles/label.styles";
import { Slot } from "@/components/ui/slot";
import type { Api } from "@zag-js/radio-group";
import { inject } from "vue";

const {
  class: className,
  asChild = false,
  ...props
} = defineProps<{
  class?: string;
  asChild?: boolean;
}>();

const api = inject<Api>("radioGroupApi");
</script>

<template>
  <Slot
    :class="cn([label, radioGroupLabel, className])"
    v-bind="{ ...api?.getLabelProps(), ...props, ...$attrs }"
  >
    <slot v-if="asChild" />
    <span v-else><slot /></span>
  </Slot>
</template>
            `}
        </PreviewCode>
        <PreviewCode title="components/ui/radio-group/RadioGroupIndicator.vue">
          {`
<script lang="ts" setup>
import { cn } from "@midoneui/core/utils/cn";
import { radioGroupIndicator } from "@midoneui/core/styles/radio-group.styles";
import { Slot } from "@/components/ui/slot";
import type { Api } from "@zag-js/radio-group";
import { inject } from "vue";

const {
  class: className,
  asChild = false,
  ...props
} = defineProps<{
  class?: string;
  asChild?: boolean;
}>();

const api = inject<Api>("radioGroupApi");
</script>

<template>
  <Slot
    :class="cn(radioGroupIndicator, className)"
    v-bind="{ ...api?.getIndicatorProps(), ...props, ...$attrs }"
  >
    <slot v-if="asChild" />
    <div v-else><slot /></div>
  </Slot>
</template>
            `}
        </PreviewCode>
        <PreviewCode title="components/ui/radio-group/RadioGroupItem.vue">
          {`
<script lang="ts" setup>
import { cn } from "@midoneui/core/utils/cn";
import { radioGroupItem } from "@midoneui/core/styles/radio-group.styles";
import { Slot } from "@/components/ui/slot";
import { RadioGroupItemHiddenInput } from ".";
import type { Api, ItemProps } from "@zag-js/radio-group";
import { provide, inject } from "vue";

const {
  class: className,
  asChild = false,
  ...props
} = defineProps<
  ItemProps & {
    class?: string;
    asChild?: boolean;
  }
>();

const api = inject<Api>("radioGroupApi");

provide("radioGroupItem", props);
</script>

<template>
  <Slot
    :class="cn(radioGroupItem, className)"
    v-bind="{ ...api?.getItemProps(props), ...props, ...$attrs }"
  >
    <slot v-if="asChild" />
    <label v-else>
      <slot />
      <RadioGroupItemHiddenInput />
    </label>
  </Slot>
</template>
            `}
        </PreviewCode>
        <PreviewCode title="components/ui/radio-group/RadioGroupItemText.vue">
          {`
<script lang="ts" setup>
import { cn } from "@midoneui/core/utils/cn";
import { radioGroupItemText } from "@midoneui/core/styles/radio-group.styles";
import { Slot } from "@/components/ui/slot";
import type { Api, ItemProps } from "@zag-js/radio-group";
import { inject } from "vue";

const {
  class: className,
  asChild = false,
  ...props
} = defineProps<{
  class?: string;
  asChild?: boolean;
}>();

const api = inject<Api>("radioGroupApi");
const itemProps = inject<ItemProps>("radioGroupItem");
</script>

<template>
  <Slot
    :class="cn(radioGroupItemText, className)"
    v-bind="{ ...api?.getItemTextProps(itemProps!), ...props, ...$attrs }"
  >
    <slot v-if="asChild" />
    <span v-else>
      <slot />
    </span>
  </Slot>
</template>
            `}
        </PreviewCode>
        <PreviewCode title="components/ui/radio-group/RadioGroupItemControl.vue">
          {`
<script lang="ts" setup>
import { cn } from "@midoneui/core/utils/cn";
import { radioGroupItemControl } from "@midoneui/core/styles/radio-group.styles";
import { Slot } from "@/components/ui/slot";
import type { Api, ItemProps } from "@zag-js/radio-group";
import { inject } from "vue";

const {
  class: className,
  asChild = false,
  ...props
} = defineProps<{
  class?: string;
  asChild?: boolean;
}>();

const api = inject<Api>("radioGroupApi");
const itemProps = inject<ItemProps>("radioGroupItem");
</script>

<template>
  <Slot
    :class="cn(radioGroupItemControl, className)"
    v-bind="{ ...api?.getItemControlProps(itemProps!), ...props, ...$attrs }"
  >
    <slot v-if="asChild" />
    <div v-else>
      <slot />
    </div>
  </Slot>
</template>
            `}
        </PreviewCode>
        <PreviewCode title="components/ui/radio-group/RadioGroupItemHiddenInput.vue">
          {`
<script lang="ts" setup>
import { cn } from "@midoneui/core/utils/cn";
import { radioGroupItemHiddenInput } from "@midoneui/core/styles/radio-group.styles";
import type { Api, ItemProps } from "@zag-js/radio-group";
import { inject } from "vue";

const { class: className, ...props } = defineProps<{
  class?: string;
}>();

const api = inject<Api>("radioGroupApi");
const itemProps = inject<ItemProps>("radioGroupItem");
</script>

<template>
  <input
    :class="cn(radioGroupItemHiddenInput, className)"
    v-bind="{ ...api?.getItemHiddenInputProps(itemProps!), ...props, ...$attrs }"
  />
</template>
            `}
        </PreviewCode>
        <PreviewCode title="components/ui/radio-group/index.ts">
          {`
export { default as RadioGroupRoot } from "./RadioGroupRoot.vue";
export { default as RadioGroupLabel } from "./RadioGroupLabel.vue";
export { default as RadioGroupIndicator } from "./RadioGroupIndicator.vue";
export { default as RadioGroupItem } from "./RadioGroupItem.vue";
export { default as RadioGroupItemText } from "./RadioGroupItemText.vue";
export { default as RadioGroupItemControl } from "./RadioGroupItemControl.vue";
export { default as RadioGroupItemHiddenInput } from "./RadioGroupItemHiddenInput.vue";
              `}
        </PreviewCode>
        <SectionContent>
          Update the import paths to match your project setup.
        </SectionContent>
      </div>
      <div id="usage">
        <SectionTitle>Usage</SectionTitle>
        <PreviewCode>
          {`
import {
  RadioGroupRoot,
  RadioGroupLabel,
  RadioGroupItem,
  RadioGroupItemText,
  RadioGroupItemControl,
} from "@/components/ui/radio-group";
              `}
        </PreviewCode>
        <PreviewCode>
          {`
<RadioGroupRoot defaultValue="React">
  <RadioGroupLabel>Framework</RadioGroupLabel>
  <RadioGroupItem
    v-for="framework in frameworks"
    :key="framework"
    :value="framework"
  >
    <RadioGroupItemControl />
    <RadioGroupItemText>{{ framework }}</RadioGroupItemText>
  </RadioGroupItem>
</RadioGroupRoot>
              `}
        </PreviewCode>
      </div>
    </>
  );
}

export default Main;
