// packages/vue/src/components/ui/menu/MenuContent.vue
<script lang="ts" setup>
import { MenuPositioner } from "@/components/ui/menu";
import { type Api } from "@zag-js/menu";
import { cn } from "@midoneui/core/utils/cn";
import { inject } from "vue";
import { Box } from "@/components/ui/box";
import { Slot } from "@/components/ui/slot";
import { menuContent } from "@midoneui/core/styles/menu.styles";

const {
  class: className,
  asChild = false,
  ...props
} = defineProps<{
  class?: string;
  asChild?: boolean;
}>();

const api = inject<Api>("menuApi");
</script>

<template>
  <MenuPositioner>
    <Slot
      :class="cn(menuContent, className)"
      v-bind="{ ...api?.getContentProps(), ...props, ...$attrs }"
    >
      <slot v-if="asChild" />
      <Box v-else raised="single" :class="cn(menuContent, className)">
        <div><slot /></div>
      </Box>
    </Slot>
  </MenuPositioner>
</template>

// packages/svelte/src/components/ui/menu/MenuContent.svelte
<script lang="ts">
  import { cn } from "@midoneui/core/utils/cn";
  import { menuContent, menuPositioner } from "@midoneui/core/styles/menu.styles";
  import { Box } from "@/components/ui/box";
  import { getContext } from "svelte";
  import type { Snippet } from "svelte";

  let { class: className, children, ...props }: { class?: string; children?: Snippet } & Record<string, any> = $props();
  const getApi = getContext<() => any>("menuApi");
  const api = $derived(getApi());
</script>

<div class={cn(menuPositioner)} {...api?.getPositionerProps()}>
  <div {...api?.getContentProps()} {...props}>
    <Box raised="double" class={cn(menuContent, className)}>
      {@render children?.()}
    </Box>
  </div>
</div>
