// packages/vue/src/components/ui/menu/MenuItem.vue
<script lang="ts" setup>
import { Slot } from "@/components/ui/slot";
import { type Api, type ItemProps } from "@zag-js/menu";
import { inject } from "vue";
import { cn } from "@/utils/cn";
import { menuItem } from "@midoneui/core/styles/menu.styles";

const {
  class: className,
  shortcut,
  asChild = false,
  ...props
} = defineProps<
  ItemProps & {
    class?: string;
    shortcut?: string;
    asChild?: boolean;
  }
>();

const api = inject<Api>("menuApi");
</script>

<template>
  <Slot
    :class="cn(menuItem, className)"
    v-bind="{ ...api?.getItemProps(props), ...props, ...$attrs }"
  >
    <slot v-if="asChild" />
    <div v-else>
      <div><slot /></div>
      <div>{{ shortcut }}</div>
    </div>
  </Slot>
</template>

// packages/svelte/src/components/ui/menu/MenuItem.svelte
<script lang="ts">
  import { cn } from "@midoneui/core/utils/cn";
  import { menuItem } from "@midoneui/core/styles/menu.styles";
  import { getContext } from "svelte";
  import type { Snippet } from "svelte";

  let {
    class: className,
    value,
    children,
    ...props
  }: { class?: string; value: string; children?: Snippet } & Record<string, any> = $props();

  const getApi = getContext<() => any>("menuApi");
  const api = $derived(getApi());
</script>

<div class={cn(menuItem, className)} {...api?.getItemProps({ value })} {...props}>
  {@render children?.()}
</div>
