// packages/docs/src/components/ui/badge/index.tsx
import { cn } from "@midoneui/core/utils/cn";
import {
  TooltipRoot,
  TooltipTrigger,
  TooltipContent,
} from "@/components/ui/tooltip";
import {
  badgeVariants,
  type BadgeVariants,
} from "@midoneui/core/styles/badge.styles";

function Badge({
  className,
  children,
  look,
  variant,
  content,
  ...props
}: React.ComponentProps<"span"> &
  BadgeVariants & {
    content?: string;
  }) {
  return (
    <TooltipRoot disabled={!content}>
      <TooltipTrigger asChild>
        <span
          {...props}
          className={cn(badgeVariants({ look, variant }), className)}
        >
          {children}
        </span>
      </TooltipTrigger>
      <TooltipContent>{content}</TooltipContent>
    </TooltipRoot>
  );
}

export { Badge };

// packages/svelte/src/components/ui/badge/Badge.svelte
<script lang="ts">
  import { cn } from "@midoneui/core/utils/cn";
  import { TooltipRoot, TooltipTrigger, TooltipPositioner, TooltipContent } from "@/components/ui/tooltip";
  import { badgeVariants, type BadgeVariants } from "@midoneui/core/styles/badge.styles";
  import type { Snippet } from "svelte";

  let {
    class: className,
    look,
    variant,
    content,
    children,
    ...props
  }: BadgeVariants & {
    class?: string;
    content?: string;
    children?: Snippet;
  } & Record<string, any> = $props();
</script>

<TooltipRoot disabled={!content}>
  <TooltipTrigger>
    <span class={cn(badgeVariants({ look, variant, className }))} {...props}>
      {@render children?.()}
    </span>
  </TooltipTrigger>
  <TooltipPositioner>
    <TooltipContent>{content}</TooltipContent>
  </TooltipPositioner>
</TooltipRoot>
