// packages/vue/src/components/ui/sheet/SheetRoot.vue
<script lang="ts" setup>
import { provide, computed } from "vue";
import * as dialog from "@zag-js/dialog";
import type { Props } from "@zag-js/dialog";
import { useMachine, normalizeProps } from "@zag-js/vue";

const {
  class: className,
  asChild = false,
  open = undefined,
  closeOnInteractOutside = undefined,
  ...props
} = defineProps<
  Partial<Props> & {
    class?: string;
    asChild?: boolean;
  }
>();

const service = useMachine(dialog.machine, {
  ...props,
  open,
  closeOnInteractOutside,
  id: crypto.randomUUID(),
});

const api = computed(() => dialog.connect(service, normalizeProps));

provide("sheetApi", api);
</script>

<template>
  <slot />
</template>

// packages/svelte/src/components/ui/sheet/SheetRoot.svelte
<script lang="ts">
  import * as dialog from "@zag-js/dialog";
  import { useMachine, normalizeProps } from "@zag-js/svelte";
  
  import { setContext } from "svelte";
  import type { Snippet } from "svelte";

  let {
    class: className,
    side = "right",
    children,
    ...props
  }: { class?: string; side?: "left" | "right" | "top" | "bottom"; children?: Snippet } & Record<string, any> = $props();

  const service = useMachine(dialog.machine, () => ({ ...props, id: crypto.randomUUID() }));
  const api = $derived(dialog.connect(service, normalizeProps));

  setContext("sheetApi", () => api);
  setContext("sheetSide", () => side);
</script>

{@render children?.()}
