// packages/vue/src/components/ui/sheet/SheetCloseTrigger.vue
<script lang="ts" setup>
import { cn } from "@midoneui/core/utils/cn";
import { sheetCloseTrigger } from "@midoneui/core/styles/sheet.styles";
import { Button } from "@/components/ui/button";
import type { Api } from "@zag-js/dialog";
import {
  buttonVariants,
  type ButtonVariants,
} from "@midoneui/core/styles/button.styles";
import { X } from "lucide-vue-next";
import { inject } from "vue";
import { Slot } from "@/components/ui/slot";

const {
  class: className,
  filled,
  variant,
  size,
  asChild = false,
  ...props
} = defineProps<
  ButtonVariants & {
    class?: string;
    asChild?: boolean;
  }
>();

const api = inject<Api>("sheetApi");
</script>

<template>
  <Slot v-bind="{ ...props, ...$attrs, ...api?.getCloseTriggerProps() }">
    <Button
      v-if="!$slots.default"
      :class="cn(sheetCloseTrigger, className)"
      v-bind="{ ...props }"
    >
      <X class="size-4" />
    </Button>
    <template v-else>
      <slot v-if="asChild" />
      <Button
        v-else
        :class="
          cn(buttonVariants({ filled, variant, size, className }), className)
        "
      >
        <slot />
      </Button>
    </template>
  </Slot>
</template>

// packages/svelte/src/components/ui/sheet/SheetCloseTrigger.svelte
<script lang="ts">
  import { X } from "lucide-svelte";
  import { cn } from "@midoneui/core/utils/cn";
  import { sheetCloseTrigger } from "@midoneui/core/styles/sheet.styles";
  import { getContext } from "svelte";
  import type { Snippet } from "svelte";

  let { class: className, children, ...props }: { class?: string; children?: Snippet } & Record<string, any> = $props();
  const getApi = getContext<() => any>("sheetApi");
  const api = $derived(getApi());
</script>

<button class={cn(sheetCloseTrigger, className)} {...api?.getCloseTriggerProps()} {...props}>
  {#if children}
    {@render children()}
  {:else}
    <X class="size-4" />
  {/if}
</button>
