// packages/vue/src/components/ui/label/Label.vue
<script lang="ts" setup>
import { cn } from "@/utils/cn";
import { label } from "@midoneui/core/styles/label.styles";

const { class: className, ...props } = defineProps<{
  class?: string;
}>();
</script>

<template>
  <label :class="cn(label, className)" v-bind="{ ...props }">
    <slot />
  </label>
</template>

// packages/react/src/components/ui/label/index.tsx
import { cn } from "@midoneui/core/utils/cn";
import { label } from "@midoneui/core/styles/label.styles";

function Label({
  className,
  children,
  ...props
}: React.ComponentProps<"label">) {
  return (
    <label {...props} className={cn(label, className)}>
      {children}
    </label>
  );
}

export { Label };
