// packages/vue/src/components/ui/popover/PopoverTrigger.vue
<script lang="ts" setup>
import { type Api } from "@zag-js/popover";
import { cn } from "@midoneui/core/utils/cn";
import { inject } from "vue";
import { Button } from "@/components/ui/button";
import { Slot } from "@/components/ui/slot";
import { popoverTrigger } from "@midoneui/core/styles/popover.styles";
import { PopoverIndicator } from ".";

const {
  class: className,
  asChild = false,
  ...props
} = defineProps<{
  class?: string;
  asChild?: boolean;
}>();

const api = inject<Api>("popoverApi");
</script>

<template>
  <Slot v-bind="{ ...api?.getTriggerProps(), ...props, ...$attrs }">
    <Button v-if="!asChild" :class="cn(popoverTrigger, className)">
      <slot />
      <PopoverIndicator />
    </Button>
    <slot v-else />
  </Slot>
</template>

// packages/svelte/src/components/ui/popover/PopoverTrigger.svelte
<script lang="ts">
  import { cn } from "@midoneui/core/utils/cn";
  import { popoverTrigger } from "@midoneui/core/styles/popover.styles";
  import { getContext } from "svelte";
  import type { Snippet } from "svelte";

  let { class: className, children, ...props }: { class?: string; children?: Snippet } & Record<string, any> = $props();
  const getApi = getContext<() => any>("popoverApi");
  const api = $derived(getApi());
</script>

<button class={cn(popoverTrigger, className)} {...api?.getTriggerProps()} {...props}>
  {@render children?.()}
</button>
