// packages/react/src/components/ui/label/index.tsx
import { cn } from "@midoneui/core/utils/cn";
import { label } from "@midoneui/core/styles/label.styles";

function Label({
  className,
  children,
  ...props
}: React.ComponentProps<"label">) {
  return (
    <label {...props} className={cn(label, className)}>
      {children}
    </label>
  );
}

export { Label };

// packages/svelte/src/components/ui/label/Label.svelte
<script lang="ts">
  import { cn } from "@midoneui/core/utils/cn";
  import { label } from "@midoneui/core/styles/label.styles";
  import type { Snippet } from "svelte";
  import type { HTMLLabelAttributes } from "svelte/elements";

  let {
    class: className,
    children,
    ...props
  }: {
    class?: string;
    children?: Snippet;
  } & HTMLLabelAttributes = $props();
</script>

<label class={cn(label, className)} {...props}>
  {@render children?.()}
</label>
