// packages/react/src/components/ui/textarea/index.tsx
import { cn } from "@midoneui/core/utils/cn";
import { textarea } from "@midoneui/core/styles/textarea.styles";

function Textarea({
  className,
  children,
  ...props
}: React.ComponentProps<"textarea">) {
  return <textarea className={cn(textarea, className)} {...props} />;
}

export { Textarea };

// packages/svelte/src/components/ui/textarea/Textarea.svelte
<script lang="ts">
  import { cn } from "@midoneui/core/utils/cn";
  import { textarea } from "@midoneui/core/styles/textarea.styles";
  import type { HTMLTextareaAttributes } from "svelte/elements";

  let {
    class: className,
    ...props
  }: {
    class?: string;
  } & HTMLTextareaAttributes = $props();
</script>

<textarea class={cn(textarea, className)} {...props}></textarea>
