// packages/svelte/src/components/ui/datepicker/Datepicker.svelte
<script lang="ts">
  import * as datePicker from "@zag-js/date-picker";
  import { useMachine, normalizeProps } from "@zag-js/svelte";
  import { cn } from "@midoneui/core/utils/cn";
  import {
    datePickerRoot,
    datePickerControl,
    datePickerInput,
    datePickerTrigger,
    datePickerPositioner,
    datePickerContent,
    datePickerViewControl,
    datePickerPrevTrigger,
    datePickerViewTrigger,
    datePickerNextTrigger,
    datePickerTable,
    datePickerTableHeader,
    datePickerTableRow,
    datePickerTableHead,
    datePickerTableBody,
    datePickerTableCell,
    datePickerTableCellTrigger,
  } from "@midoneui/core/styles/datepicker.styles";
  import { Box } from "@/components/ui/box";
  import { Calendar, ChevronLeft, ChevronRight } from "lucide-svelte";
  import { input } from "@midoneui/core/styles/input.styles";

  let {
    class: className,
    ...props
  }: { class?: string } & Record<string, any> = $props();

  const service = useMachine(datePicker.machine, () => ({
    ...props,
    id: crypto.randomUUID(),
    locale: "en",
  }));

  const api = $derived(datePicker.connect(service, normalizeProps));
</script>

<div class={cn(datePickerRoot, className)} {...api.getRootProps()}>
  <div class={cn(datePickerControl)} {...api.getControlProps()}>
    <input class={cn(input, datePickerInput)} {...api.getInputProps()} />
    <button class={cn(datePickerTrigger)} {...api.getTriggerProps()}>
      <Calendar class="size-4" />
    </button>
  </div>
  <div class={cn(datePickerPositioner)} {...api.getPositionerProps()}>
    <div {...api.getContentProps()}>
      <Box raised="double" class={cn(datePickerContent)}>
        <div>
          {#if api.view === "day"}
            <div class={cn(datePickerViewControl)}>
              <button class={cn(datePickerPrevTrigger)} {...api.getPrevTriggerProps()}>
                <ChevronLeft class="size-4" />
              </button>
              <button class={cn(datePickerViewTrigger)} {...api.getViewTriggerProps()}>
                {api.visibleRangeText.start}
              </button>
              <button class={cn(datePickerNextTrigger)} {...api.getNextTriggerProps()}>
                <ChevronRight class="size-4" />
              </button>
            </div>
            <table class={cn(datePickerTable)} {...api.getTableProps({ view: "day" })}>
              <thead class={cn(datePickerTableHeader)} {...api.getTableHeaderProps({ view: "day" })}>
                <tr class={cn(datePickerTableRow)}>
                  {#each api.weekDays as day}
                    <th class={cn(datePickerTableHead)}>{day.narrow}</th>
                  {/each}
                </tr>
              </thead>
              <tbody class={cn(datePickerTableBody)} {...api.getTableBodyProps({ view: "day" })}>
                {#each api.weeks as week}
                  <tr class={cn(datePickerTableRow)}>
                    {#each week as value}
                      <td class={cn(datePickerTableCell)} {...api.getDayTableCellProps({ value })}>
                        <div class={cn(datePickerTableCellTrigger)} {...api.getDayTableCellTriggerProps({ value })}>
                          {value.day}
                        </div>
                      </td>
                    {/each}
                  </tr>
                {/each}
              </tbody>
            </table>
          {:else if api.view === "month"}
            <div class={cn(datePickerViewControl)}>
              <button class={cn(datePickerPrevTrigger)} {...api.getPrevTriggerProps()}>
                <ChevronLeft class="size-4" />
              </button>
              <button class={cn(datePickerViewTrigger)} {...api.getViewTriggerProps()}>
                {api.visibleRange.start.year}
              </button>
              <button class={cn(datePickerNextTrigger)} {...api.getNextTriggerProps()}>
                <ChevronRight class="size-4" />
              </button>
            </div>
            <table class={cn(datePickerTable)} {...api.getTableProps({ view: "month", columns: 4 })}>
              <tbody class={cn(datePickerTableBody)} {...api.getTableBodyProps({ view: "month" })}>
                {#each api.getMonthsGrid({ columns: 4, format: "short" }) as months}
                  <tr class={cn(datePickerTableRow)}>
                    {#each months as month}
                      <td class={cn(datePickerTableCell)} {...api.getMonthTableCellProps({ ...month, columns: 4 })}>
                        <div class={cn(datePickerTableCellTrigger)} {...api.getMonthTableCellTriggerProps({ ...month, columns: 4 })}>
                          {month.label}
                        </div>
                      </td>
                    {/each}
                  </tr>
                {/each}
              </tbody>
            </table>
          {:else}
            <div class={cn(datePickerViewControl)}>
              <button class={cn(datePickerPrevTrigger)} {...api.getPrevTriggerProps()}>
                <ChevronLeft class="size-4" />
              </button>
              <button class={cn(datePickerViewTrigger)} {...api.getViewTriggerProps()}>
                {api.getDecade().start} - {api.getDecade().end}
              </button>
              <button class={cn(datePickerNextTrigger)} {...api.getNextTriggerProps()}>
                <ChevronRight class="size-4" />
              </button>
            </div>
            <table class={cn(datePickerTable)} {...api.getTableProps({ view: "year", columns: 4 })}>
              <tbody class={cn(datePickerTableBody)} {...api.getTableBodyProps({ view: "year" })}>
                {#each api.getYearsGrid({ columns: 4 }) as years}
                  <tr class={cn(datePickerTableRow)}>
                    {#each years as year}
                      <td class={cn(datePickerTableCell)} {...api.getYearTableCellProps({ ...year, columns: 4 })}>
                        <div class={cn(datePickerTableCellTrigger)} {...api.getYearTableCellTriggerProps({ ...year, columns: 4 })}>
                          {year.label}
                        </div>
                      </td>
                    {/each}
                  </tr>
                {/each}
              </tbody>
            </table>
          {/if}
        </div>
      </Box>
    </div>
  </div>
</div>

// packages/react/src/components/ui/datepicker/index.tsx
import { Input } from "@/components/ui/input";
import { Box } from "@/components/ui/box";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import {
  NativeSelect,
  NativeSelectOption,
} from "@/components/ui/native-select";
import { cn } from "@midoneui/core/utils/cn";
import { createContext, useContext, useEffect, useId, useState } from "react";
import * as datepicker from "@zag-js/date-picker";
import type {
  Api,
  Props,
  PresetTriggerProps,
  DayTableCellProps,
  TableCellProps,
  ViewProps,
  InputProps,
} from "@zag-js/date-picker";
import { Slot } from "@/components/ui/slot";
import { useMachine, normalizeProps, Portal } from "@zag-js/react";
import { Calendar, MoveLeft, MoveRight, X } from "lucide-react";
import {
  datePickerRoot,
  datePickerLabel,
  datePickerControl,
  datePickerInput,
  datePickerTrigger,
  datePickerClearTrigger,
  datePickerPositioner,
  datePickerContent,
  datePickerYearSelect,
  datePickerMonthSelect,
  datePickerView,
  datePickerViewControl,
  datePickerPresetTrigger,
  datePickerPrevTrigger,
  datePickerViewTrigger,
  datePickerNextTrigger,
  datePickerRangeText,
  datePickerTable,
  datePickerTableHead,
  datePickerTableRow,
  datePickerTableHeader,
  datePickerTableBody,
  datePickerTableCell,
  datePickerTableCellTrigger,
} from "@midoneui/core/styles/datepicker.styles";

const ApiContext = createContext<Api | null>(null);
const ViewContext = createContext<ViewProps | null>(null);
const CellContext = createContext<DayTableCellProps | TableCellProps | null>(
  null
);
const RegistrationContext = createContext<((isManual: boolean) => void) | null>(
  null
);

export function DatePickerRoot({
  children,
  className,
  asChild = false,
  label,
  ...props
}: React.ComponentProps<"div"> &
  Partial<Props> & { asChild?: boolean; label?: string }) {
  const service = useMachine(datepicker.machine, {
    ...props,
    id: useId(),
  });
  const api = datepicker.connect(service, normalizeProps);
  const [hasManualContent, setHasManualContent] = useState(false);

  const registerContent = (isManual: boolean) => {
    if (isManual) {
      setHasManualContent(true);
    }
  };

  return (
    <ApiContext.Provider value={api}>
      <RegistrationContext.Provider value={registerContent}>
        <Slot
          className={cn(datePickerRoot, className)}
          {...api.getRootProps()}
          {...props}
        >
          {asChild ? (
            children
          ) : (
            <div>
              {!children ? (
                <>
                  {label && <DatePickerLabel>{label}</DatePickerLabel>}
                  <DatePickerControl />
                </>
              ) : (
                children
              )}
              {!hasManualContent && (
                <DatePickerPositioner isManual={false}>
                  <DatePickerContent isManual={false} />
                </DatePickerPositioner>
              )}
            </div>
          )}
        </Slot>
      </RegistrationContext.Provider>
    </ApiContext.Provider>
  );
}

export function DatePickerContext({
  children,
}: {
  children: (api: Api) => React.ReactNode;
}) {
  const api = useContext(ApiContext);

  return children(api!);
}

export function DatePickerLabel({
  children,
  className,
  asChild = false,
  ...props
}: React.ComponentProps<"label"> & { asChild?: boolean }) {
  const api = useContext(ApiContext);

  return (
    <Slot {...api?.getLabelProps()} {...props}>
      {asChild ? (
        children
      ) : (
        <Label className={cn(datePickerLabel, className)}>{children}</Label>
      )}
    </Slot>
  );
}

export function DatePickerControl({
  children,
  className,
  asChild = false,
  ...props
}: React.ComponentProps<"div"> & { asChild?: boolean }) {
  const api = useContext(ApiContext);

  return (
    <Slot
      className={cn(datePickerControl, className)}
      {...api?.getControlProps()}
      {...props}
    >
      {asChild ? (
        children
      ) : (
        <div>
          {!children ? (
            <>
              <DatePickerInput />
              <DatePickerTrigger />
              <DatePickerClearTrigger>Clear</DatePickerClearTrigger>
            </>
          ) : (
            children
          )}
        </div>
      )}
    </Slot>
  );
}

export function DatePickerInput({
  children,
  className,
  asChild = false,
  ...props
}: React.ComponentProps<"input"> & InputProps & { asChild?: boolean }) {
  const api = useContext(ApiContext);

  return (
    <Slot {...api?.getInputProps(props)} {...props}>
      {asChild ? (
        children
      ) : (
        <Input className={cn(datePickerInput, className)} />
      )}
    </Slot>
  );
}

export function DatePickerTrigger({
  children,
  asChild,
  className,
  ...props
}: React.ComponentProps<"button"> & { asChild?: boolean }) {
  const api = useContext(ApiContext);

  return (
    <Slot {...api?.getTriggerProps()} {...props}>
      {!asChild ? (
        <Button variant="ghost" className={cn(datePickerTrigger, className)}>
          {!children ? <Calendar /> : children}
        </Button>
      ) : (
        children
      )}
    </Slot>
  );
}

export function DatePickerClearTrigger({
  children,
  asChild,
  className,
  ...props
}: React.ComponentProps<"button"> & { asChild?: boolean }) {
  const api = useContext(ApiContext);

  return (
    <Slot {...api?.getClearTriggerProps()} {...props}>
      {!asChild ? (
        <Button
          variant="ghost"
          className={cn(datePickerClearTrigger, className)}
        >
          {!children ? <X /> : children}
        </Button>
      ) : (
        children
      )}
    </Slot>
  );
}

export function DatePickerPositioner({
  children,
  asChild,
  className,
  isManual = true,
  ...props
}: React.ComponentProps<"div"> & {
  asChild?: boolean;
  isManual?: boolean;
}) {
  const api = useContext(ApiContext);
  const register = useContext(RegistrationContext);

  useEffect(() => {
    if (isManual && register) {
      register(true);
    }
  }, [isManual, register]);

  if (!api?.open) return null;

  return (
    <Portal>
      <Slot
        className={cn(datePickerPositioner, className)}
        {...api?.getPositionerProps()}
        {...props}
      >
        {asChild ? children : <div>{children}</div>}
      </Slot>
    </Portal>
  );
}

export function DatePickerContent({
  children,
  asChild,
  className,
  isManual = true,
  ...props
}: React.ComponentProps<"div"> & {
  asChild?: boolean;
  isManual?: boolean;
}) {
  const api = useContext(ApiContext);
  const register = useContext(RegistrationContext);

  useEffect(() => {
    if (isManual && register) {
      register(true);
    }
  }, [isManual, register]);

  return (
    <Slot {...api?.getContentProps()} {...props}>
      {asChild ? (
        children
      ) : (
        <Box raised="single" className={cn(datePickerContent, className)}>
          <div>
            {!children ? (
              <>
                <DatePickerYearSelect />
                <DatePickerMonthSelect />
                <DatePickerView view="day" isManual={false}>
                  <DatePickerContext>
                    {(api) => (
                      <>
                        <DatePickerViewControl>
                          <DatePickerPrevTrigger />
                          <DatePickerViewTrigger>
                            <DatePickerRangeText />
                          </DatePickerViewTrigger>
                          <DatePickerNextTrigger />
                        </DatePickerViewControl>
                        <DatePickerTable>
                          <DatePickerTableHead>
                            <DatePickerTableRow>
                              {api.weekDays.map((weekDay, id) => (
                                <DatePickerTableHeader key={id}>
                                  {weekDay.short}
                                </DatePickerTableHeader>
                              ))}
                            </DatePickerTableRow>
                          </DatePickerTableHead>
                          <DatePickerTableBody>
                            {api.weeks.map((week, id) => (
                              <DatePickerTableRow key={id}>
                                {week.map((day, id) => (
                                  <DatePickerTableCell key={id} value={day}>
                                    <DatePickerTableCellTrigger>
                                      {day.day}
                                    </DatePickerTableCellTrigger>
                                  </DatePickerTableCell>
                                ))}
                              </DatePickerTableRow>
                            ))}
                          </DatePickerTableBody>
                        </DatePickerTable>
                      </>
                    )}
                  </DatePickerContext>
                </DatePickerView>
                <DatePickerView view="month" isManual={false}>
                  <DatePickerContext>
                    {(api) => (
                      <>
                        <DatePickerViewControl>
                          <DatePickerPrevTrigger />
                          <DatePickerViewTrigger>
                            <DatePickerRangeText />
                          </DatePickerViewTrigger>
                          <DatePickerNextTrigger />
                        </DatePickerViewControl>
                        <DatePickerTable>
                          <DatePickerTableBody>
                            {api
                              .getMonthsGrid({ columns: 4, format: "short" })
                              .map((months, id) => (
                                <DatePickerTableRow key={id}>
                                  {months.map((month, id) => (
                                    <DatePickerTableCell
                                      key={id}
                                      value={month.value}
                                    >
                                      <DatePickerTableCellTrigger>
                                        {month.label}
                                      </DatePickerTableCellTrigger>
                                    </DatePickerTableCell>
                                  ))}
                                </DatePickerTableRow>
                              ))}
                          </DatePickerTableBody>
                        </DatePickerTable>
                      </>
                    )}
                  </DatePickerContext>
                </DatePickerView>
                <DatePickerView view="year" isManual={false}>
                  <DatePickerContext>
                    {(api) => (
                      <>
                        <DatePickerViewControl>
                          <DatePickerPrevTrigger />
                          <DatePickerViewTrigger>
                            <DatePickerRangeText />
                          </DatePickerViewTrigger>
                          <DatePickerNextTrigger />
                        </DatePickerViewControl>
                        <DatePickerTable>
                          <DatePickerTableBody>
                            {api
                              .getYearsGrid({ columns: 4 })
                              .map((years, id) => (
                                <DatePickerTableRow key={id}>
                                  {years.map((year, id) => (
                                    <DatePickerTableCell
                                      key={id}
                                      value={year.value}
                                    >
                                      <DatePickerTableCellTrigger>
                                        {year.label}
                                      </DatePickerTableCellTrigger>
                                    </DatePickerTableCell>
                                  ))}
                                </DatePickerTableRow>
                              ))}
                          </DatePickerTableBody>
                        </DatePickerTable>
                      </>
                    )}
                  </DatePickerContext>
                </DatePickerView>
              </>
            ) : (
              children
            )}
          </div>
        </Box>
      )}
    </Slot>
  );
}

export function DatePickerYearSelect({
  children,
  className,
  ...props
}: React.ComponentProps<"select">) {
  const api = useContext(ApiContext);

  return (
    <NativeSelect
      className={cn(datePickerYearSelect, className)}
      {...api?.getYearSelectProps()}
      {...props}
    >
      {api?.getYears().map((year, i) => (
        <NativeSelectOption key={i} value={year.value}>
          {year.label}
        </NativeSelectOption>
      ))}
    </NativeSelect>
  );
}

export function DatePickerMonthSelect({
  children,
  className,
  ...props
}: React.ComponentProps<"select">) {
  const api = useContext(ApiContext);

  return (
    <NativeSelect
      className={cn(datePickerMonthSelect, className)}
      {...api?.getMonthSelectProps()}
      {...props}
    >
      {api?.getMonths().map((month, i) => (
        <NativeSelectOption key={i} value={month.value}>
          {month.label}
        </NativeSelectOption>
      ))}
    </NativeSelect>
  );
}

export function DatePickerView({
  children,
  asChild,
  className,
  isManual = true,
  ...props
}: React.ComponentProps<"div"> &
  ViewProps & {
    asChild?: boolean;
    isManual?: boolean;
  }) {
  const api = useContext(ApiContext);
  const register = useContext(RegistrationContext);

  useEffect(() => {
    if (isManual && register) {
      register(true);
    }
  }, [isManual, register]);

  return (
    <ViewContext.Provider value={props}>
      <Slot
        className={cn(datePickerView, className)}
        {...api?.getViewProps(props)}
        {...props}
      >
        {asChild ? children : <div>{children}</div>}
      </Slot>
    </ViewContext.Provider>
  );
}

export function DatePickerViewControl({
  children,
  asChild,
  className,
  ...props
}: React.ComponentProps<"div"> & { asChild?: boolean }) {
  const api = useContext(ApiContext);

  return (
    <Slot
      className={cn(datePickerViewControl, className)}
      {...api?.getViewControlProps()}
      {...props}
    >
      {asChild ? children : <div>{children}</div>}
    </Slot>
  );
}

export function DatePickerPresetTrigger({
  children,
  asChild,
  className,
  ...props
}: React.ComponentProps<"button"> &
  PresetTriggerProps & { asChild?: boolean }) {
  const api = useContext(ApiContext);

  return (
    <Slot {...api?.getPresetTriggerProps(props)} {...props}>
      {!asChild ? (
        <Button
          variant="ghost"
          className={cn(datePickerPresetTrigger, className)}
        >
          {children}
        </Button>
      ) : (
        children
      )}
    </Slot>
  );
}

export function DatePickerPrevTrigger({
  children,
  asChild,
  className,
  ...props
}: React.ComponentProps<"button"> & { asChild?: boolean }) {
  const api = useContext(ApiContext);

  return (
    <Slot {...api?.getPrevTriggerProps()} {...props}>
      {!asChild ? (
        <button className={cn(datePickerPrevTrigger, className)}>
          {!children ? <MoveLeft /> : children}
        </button>
      ) : (
        children
      )}
    </Slot>
  );
}

export function DatePickerViewTrigger({
  children,
  asChild,
  className,
  ...props
}: React.ComponentProps<"button"> & { asChild?: boolean }) {
  const api = useContext(ApiContext);

  return (
    <Slot {...api?.getViewTriggerProps()} {...props}>
      {!asChild ? (
        <button className={cn(datePickerViewTrigger, className)}>
          {children}
        </button>
      ) : (
        children
      )}
    </Slot>
  );
}

export function DatePickerNextTrigger({
  children,
  asChild,
  className,
  ...props
}: React.ComponentProps<"button"> & { asChild?: boolean }) {
  const api = useContext(ApiContext);

  return (
    <Slot {...api?.getNextTriggerProps()} {...props}>
      {!asChild ? (
        <button className={cn(datePickerNextTrigger, className)}>
          {!children ? <MoveRight /> : children}
        </button>
      ) : (
        children
      )}
    </Slot>
  );
}

export function DatePickerRangeText({
  children,
  className,
  ...props
}: React.ComponentProps<"div">) {
  const api = useContext(ApiContext);

  return (
    <div
      className={cn(datePickerRangeText, className)}
      {...api?.getRangeTextProps()}
      {...props}
    >
      {api?.visibleRangeText.start}
    </div>
  );
}

export function DatePickerTable({
  children,
  asChild,
  className,
  ...props
}: React.ComponentProps<"table"> & { asChild?: boolean }) {
  const api = useContext(ApiContext);

  return (
    <Slot
      className={cn(datePickerTable, className)}
      {...api?.getTableProps()}
      {...props}
    >
      {asChild ? children : <table>{children}</table>}
    </Slot>
  );
}

export function DatePickerTableHead({
  children,
  asChild,
  className,
  ...props
}: React.ComponentProps<"thead"> & { asChild?: boolean }) {
  const api = useContext(ApiContext);

  return (
    <Slot
      className={cn(datePickerTableHead, className)}
      {...api?.getTableHeadProps()}
      {...props}
    >
      {asChild ? children : <thead>{children}</thead>}
    </Slot>
  );
}

export function DatePickerTableRow({
  children,
  asChild,
  className,
  ...props
}: React.ComponentProps<"tr"> & { asChild?: boolean }) {
  const api = useContext(ApiContext);

  return (
    <Slot
      className={cn(datePickerTableRow, className)}
      {...api?.getTableRowProps()}
      {...props}
    >
      {asChild ? children : <tr>{children}</tr>}
    </Slot>
  );
}

export function DatePickerTableHeader({
  children,
  asChild,
  className,
  ...props
}: React.ComponentProps<"th"> & { asChild?: boolean }) {
  const api = useContext(ApiContext);

  return (
    <Slot
      className={cn(datePickerTableHeader, className)}
      {...api?.getTableHeaderProps()}
      {...props}
    >
      {asChild ? children : <th>{children}</th>}
    </Slot>
  );
}

export function DatePickerTableBody({
  children,
  asChild,
  className,
  ...props
}: React.ComponentProps<"tbody"> & { asChild?: boolean }) {
  const api = useContext(ApiContext);

  return (
    <Slot
      className={cn(datePickerTableBody, className)}
      {...api?.getTableHeadProps()}
      {...props}
    >
      {asChild ? children : <tbody>{children}</tbody>}
    </Slot>
  );
}

export function DatePickerTableCell({
  children,
  asChild,
  className,
  ...props
}: React.ComponentProps<"td"> &
  (DayTableCellProps | TableCellProps) & { asChild?: boolean }) {
  const api = useContext(ApiContext);
  const viewContext = useContext(ViewContext);

  return (
    <CellContext.Provider value={props}>
      <Slot
        className={cn(datePickerTableCell, className)}
        {...(viewContext?.view === "day"
          ? api?.getDayTableCellProps(props as DayTableCellProps)
          : viewContext?.view === "month"
          ? api?.getMonthTableCellProps(props as TableCellProps)
          : viewContext?.view === "year"
          ? api?.getYearTableCellProps(props as TableCellProps)
          : undefined)}
        {...props}
      >
        {asChild ? children : <td>{children}</td>}
      </Slot>
    </CellContext.Provider>
  );
}

export function DatePickerTableCellTrigger({
  children,
  asChild,
  className,
  ...props
}: React.ComponentProps<"td"> & { asChild?: boolean }) {
  const api = useContext(ApiContext);
  const viewContext = useContext(ViewContext);
  const cellContext = useContext(CellContext);

  return (
    <Slot
      className={cn(datePickerTableCellTrigger, className)}
      {...(viewContext?.view === "day"
        ? api?.getDayTableCellTriggerProps(cellContext as DayTableCellProps)
        : viewContext?.view === "month"
        ? api?.getMonthTableCellTriggerProps(cellContext as TableCellProps)
        : viewContext?.view === "year"
        ? api?.getYearTableCellTriggerProps(cellContext as TableCellProps)
        : undefined)}
      {...props}
    >
      {asChild ? children : <div>{children}</div>}
    </Slot>
  );
}
