// packages/svelte/src/components/ui/sheet/SheetContent.svelte
<script lang="ts">
  import { cn } from "@midoneui/core/utils/cn";
  import { sheetBackdrop, sheetContent, sheetPositioner } from "@midoneui/core/styles/sheet.styles";
  import { getContext } from "svelte";
  import type { Snippet } from "svelte";

  let { class: className, children, ...props }: { class?: string; children?: Snippet } & Record<string, any> = $props();
  const getApi = getContext<() => any>("sheetApi");
  const getSide = getContext<() => string>("sheetSide");
  const api = $derived(getApi());
  const side = $derived(getSide());
</script>

<div class={cn(sheetBackdrop)} {...api?.getBackdropProps()}></div>
<div class={cn(sheetPositioner)} {...api?.getPositionerProps()}>
  <div {...api?.getContentProps()} class={cn(sheetContent, className)} data-side={side} {...props}>
    {@render children?.()}
  </div>
</div>

// packages/vue/src/components/ui/sheet/SheetContent.vue
<script lang="ts" setup>
import { cn } from "@/utils/cn";
import { sheetContent } from "@midoneui/core/styles/sheet.styles";
import { Box } from "@/components/ui/box";
import { SheetBackdrop, SheetPositioner } from "@/components/ui/sheet";
import type { Api } from "@zag-js/dialog";
import { inject } from "vue";
import { Slot } from "@/components/ui/slot";

const {
  class: className,
  asChild = false,
  side = "right",
  ...props
} = defineProps<{
  class?: string;
  asChild?: boolean;
  side?: "top" | "right" | "bottom" | "left";
}>();

const api = inject<Api>("sheetApi");
</script>

<template>
  <Teleport to="body">
    <SheetBackdrop />
    <SheetPositioner>
      <Slot v-bind="{ ...props, ...$attrs, ...api?.getContentProps() }">
        <slot v-if="asChild" />
        <div v-else>
          <Box
            raised="double"
            :data-side="side"
            :class="cn(sheetContent, className)"
            v-bind="{ ...props }"
          >
            <div><slot /></div>
          </Box>
        </div>
      </Slot>
    </SheetPositioner>
  </Teleport>
</template>
