// packages/svelte/src/components/ui/tabs/TabsList.svelte
<script lang="ts">
  import { cn } from "@midoneui/core/utils/cn";
  import { tabsList, tabsIndicator } from "@midoneui/core/styles/tabs.styles";
  import { getContext } from "svelte";
  import type { Snippet } from "svelte";

  let { class: className, children, ...props }: { class?: string; children?: Snippet } & Record<string, any> = $props();
  const getApi = getContext<() => any>("tabsApi");
  const api = $derived(getApi());
</script>

<div class={cn(tabsList, className)} {...api?.getListProps()} {...props}>
  {@render children?.()}
  <div class={cn(tabsIndicator)} {...api?.getIndicatorProps()}></div>
</div>

// packages/vue/src/components/ui/tabs/TabsList.vue
<script lang="ts" setup>
import { cn } from "@/utils/cn";
import { tabsList } from "@midoneui/core/styles/tabs.styles";
import type { Api } from "@zag-js/tabs";
import { inject } from "vue";
import { Slot } from "@/components/ui/slot";
import { TabsIndicator } from ".";

const {
  class: className,
  asChild = false,
  ...props
} = defineProps<{
  class?: string;
  asChild?: boolean;
}>();

const api = inject<Api>("tabsApi");
</script>

<template>
  <Slot
    :class="cn(tabsList, className)"
    v-bind="{ ...props, ...$attrs, ...api?.getListProps() }"
  >
    <slot v-if="asChild" />
    <div v-else>
      <slot />
      <TabsIndicator />
    </div>
  </Slot>
</template>
