// packages/svelte/src/components/ui/tooltip/TooltipContent.svelte
<script lang="ts">
  import { cn } from "@midoneui/core/utils/cn";
  import { tooltipContent } from "@midoneui/core/styles/tooltip.styles";
  import { TooltipArrow, TooltipArrowTip } from ".";
  import { getContext } from "svelte";
  import type { Snippet } from "svelte";

  let {
    class: className,
    children,
    ...props
  }: {
    class?: string;
    children?: Snippet;
  } & Record<string, any> = $props();

  const getApi = getContext<() => any>("tooltipApi");
  const api = $derived(getApi());
</script>

<div class={cn(tooltipContent, className)} {...api?.getContentProps()} {...props}>
  {@render children?.()}
  <TooltipArrow>
    <TooltipArrowTip />
  </TooltipArrow>
</div>

// packages/vue/src/components/ui/tooltip/TooltipContent.vue
<script lang="ts" setup>
import { cn } from "@/utils/cn";
import { tooltipContent } from "@midoneui/core/styles/tooltip.styles";
import { Slot } from "@/components/ui/slot";
import { TooltipArrow, TooltipArrowTip, TooltipPositioner } from ".";
import type { Api } from "@zag-js/tooltip";
import { inject } from "vue";

const {
  class: className,
  asChild = false,
  ...props
} = defineProps<{
  class?: string;
  asChild?: boolean;
}>();

const api = inject<Api>("tooltipApi");
</script>

<template>
  <TooltipPositioner>
    <Slot
      :class="cn(tooltipContent, className)"
      v-bind="{ ...api?.getContentProps(), ...props, ...$attrs }"
    >
      <slot v-if="asChild" />
      <div v-else>
        <slot />
        <TooltipArrow>
          <TooltipArrowTip />
        </TooltipArrow>
      </div>
    </Slot>
  </TooltipPositioner>
</template>
