// packages/svelte/src/components/ui/dialog/DialogCloseTrigger.svelte
<script lang="ts">
  import { X } from "lucide-svelte";
  import { cn } from "@midoneui/core/utils/cn";
  import { dialogCloseTrigger } from "@midoneui/core/styles/dialog.styles";
  import { Button } from "@/components/ui/button";
  import { getContext } from "svelte";
  import type { Snippet } from "svelte";

  let { class: className, children, ...props }: { class?: string; children?: Snippet } & Record<string, any> = $props();
  const getApi = getContext<() => any>("dialogApi");
  const api = $derived(getApi());
</script>

{#if children}
  <Button variant="secondary" look="outline" class={className} {...api?.getCloseTriggerProps()} {...props}>
    {@render children()}
  </Button>
{:else}
  <Button variant="ghost" class={cn(dialogCloseTrigger, className)} {...api?.getCloseTriggerProps()} {...props}>
    <X class="size-4" />
  </Button>
{/if}

// packages/vue/src/components/ui/dialog/DialogCloseTrigger.vue
<script lang="ts" setup>
import { cn } from "@midoneui/core/utils/cn";
import { dialogCloseTrigger } from "@midoneui/core/styles/dialog.styles";
import { Button } from "@/components/ui/button";
import type { Api } from "@zag-js/dialog";
import {
  buttonVariants,
  type ButtonVariants,
} from "@midoneui/core/styles/button.styles";
import { X } from "lucide-vue-next";
import { inject } from "vue";
import { Slot } from "@/components/ui/slot";

const {
  class: className,
  look = "outline",
  variant = "secondary",
  size,
  asChild = false,
  ...props
} = defineProps<
  ButtonVariants & {
    class?: string;
    asChild?: boolean;
  }
>();

const api = inject<Api>("dialogApi");
</script>

<template>
  <Slot v-bind="{ ...props, ...$attrs, ...api?.getCloseTriggerProps() }">
    <Button
      variant="ghost"
      v-if="!$slots.default"
      :class="cn(dialogCloseTrigger, className)"
      v-bind="{ ...props }"
    >
      <X class="size-4" />
    </Button>
    <template v-else>
      <slot v-if="asChild" />
      <Button
        v-else
        :class="
          cn(buttonVariants({ look, variant, size }), className)
        "
      >
        <slot />
      </Button>
    </template>
  </Slot>
</template>
