// packages/svelte/src/components/ui/dialog/DialogPositioner.svelte
<script lang="ts">
  import { cn } from "@midoneui/core/utils/cn";
  import { dialogPositioner } from "@midoneui/core/styles/dialog.styles";
  import { getContext } from "svelte";
  import type { Snippet } from "svelte";

  let { class: className, children, ...props }: { class?: string; children?: Snippet } & Record<string, any> = $props();
  const getApi = getContext<() => any>("dialogApi");
  const api = $derived(getApi());
</script>

<div class={cn(dialogPositioner, className)} {...api?.getPositionerProps()} {...props}>
  {@render children?.()}
</div>

// packages/vue/src/components/ui/dialog/DialogPositioner.vue
<script lang="ts" setup>
import { cn } from "@/utils/cn";
import { dialogPositioner } from "@midoneui/core/styles/dialog.styles";
import type { Api } from "@zag-js/dialog";
import { inject } from "vue";
import { Slot } from "@/components/ui/slot";

const {
  class: className,
  asChild = false,
  ...props
} = defineProps<{
  class?: string;
  asChild?: boolean;
}>();

const api = inject<Api>("dialogApi");
</script>

<template>
  <Slot
    :class="cn(dialogPositioner, className)"
    v-bind="{ ...props, ...$attrs, ...api?.getPositionerProps() }"
  >
    <slot v-if="asChild" />
    <div v-else>
      <slot />
    </div>
  </Slot>
</template>
