// packages/svelte/src/components/ui/dialog/DialogRoot.svelte
<script lang="ts">
  import * as dialog from "@zag-js/dialog";
  import { useMachine, normalizeProps } from "@zag-js/svelte";
  import { setContext } from "svelte";
  import type { Snippet } from "svelte";

  let {
    open = undefined,
    closeOnInteractOutside = undefined,
    children,
    ...props
  }: { open?: boolean; closeOnInteractOutside?: boolean; children?: Snippet } & Record<string, any> = $props();

  const service = useMachine(dialog.machine, () => ({ ...props, open, closeOnInteractOutside, id: crypto.randomUUID() }));
  const api = $derived(dialog.connect(service, normalizeProps));

  setContext("dialogApi", () => api);
</script>

{@render children?.()}

// packages/vue/src/components/ui/dialog/DialogRoot.vue
<script lang="ts" setup>
import { provide, computed } from "vue";
import * as dialog from "@zag-js/dialog";
import type { Props } from "@zag-js/dialog";
import { useMachine, normalizeProps } from "@zag-js/vue";

const {
  class: className,
  asChild = false,
  open = undefined,
  closeOnInteractOutside = undefined,
  ...props
} = defineProps<
  Partial<Props> & {
    class?: string;
    asChild?: boolean;
  }
>();

const service = useMachine(dialog.machine, {
  ...props,
  open,
  closeOnInteractOutside,
  id: crypto.randomUUID(),
});

const api = computed(() => dialog.connect(service, normalizeProps));

provide("dialogApi", api);
</script>

<template>
  <slot />
</template>
