// packages/vue/src/components/ui/tooltip/TooltipTrigger.vue
<script lang="ts" setup>
import { cn } from "@midoneui/core/utils/cn";
import { tooltipTrigger } from "@midoneui/core/styles/tooltip.styles";
import { Slot } from "@/components/ui/slot";
import { Button } from "@/components/ui/button";
import type { Api } from "@zag-js/tooltip";
import { inject } from "vue";

const {
  class: className,
  asChild = false,
  ...props
} = defineProps<{
  class?: string;
  asChild?: boolean;
}>();

const api = inject<Api>("tooltipApi");
</script>

<template>
  <Slot v-bind="{ ...api?.getTriggerProps(), ...props, ...$attrs }">
    <Button v-if="!asChild" :class="cn(tooltipTrigger, className)">
      <slot />
    </Button>
    <slot v-else />
  </Slot>
</template>

// packages/svelte/src/components/ui/tooltip/TooltipTrigger.svelte
<script lang="ts">
  import { cn } from "@midoneui/core/utils/cn";
  import { getContext } from "svelte";
  import type { Snippet } from "svelte";

  let {
    class: className,
    children,
    ...props
  }: {
    class?: string;
    children?: Snippet;
  } & Record<string, any> = $props();

  const getApi = getContext<() => any>("tooltipApi");
  const api = $derived(getApi());
</script>

<button {...api?.getTriggerProps()} {...props}>
  {@render children?.()}
</button>
