// packages/vue/src/components/ui/tooltip/TooltipArrow.vue
<script lang="ts" setup>
import { cn } from "@/utils/cn";
import { tooltipArrow } from "@midoneui/core/styles/tooltip.styles";
import { Slot } from "@/components/ui/slot";
import type { Api } from "@zag-js/tooltip";
import { inject } from "vue";

const {
  class: className,
  asChild = false,
  ...props
} = defineProps<{
  class?: string;
  asChild?: boolean;
}>();

const api = inject<Api>("tooltipApi");
</script>

<template>
  <Slot
    :class="cn(tooltipArrow, className)"
    v-bind="{ ...api?.getArrowProps(), ...props, ...$attrs }"
  >
    <slot v-if="asChild" />
    <div v-else>
      <slot />
    </div>
  </Slot>
</template>

// packages/svelte/src/components/ui/tooltip/TooltipArrow.svelte
<script lang="ts">
  import { cn } from "@midoneui/core/utils/cn";
  import { tooltipArrow } from "@midoneui/core/styles/tooltip.styles";
  import { getContext } from "svelte";
  import type { Snippet } from "svelte";

  let {
    class: className,
    children,
    ...props
  }: {
    class?: string;
    children?: Snippet;
  } & Record<string, any> = $props();

  const getApi = getContext<() => any>("tooltipApi");
  const api = $derived(getApi());
</script>

<div class={cn(tooltipArrow, className)} {...api?.getArrowProps()} {...props}>
  {@render children?.()}
</div>
