// packages/vue/src/components/ui/tooltip/TooltipRoot.vue
<script lang="ts" setup>
import * as tooltip from "@zag-js/tooltip";
import type { Props } from "@zag-js/tooltip";
import { normalizeProps, useMachine } from "@zag-js/vue";
import { computed, provide } from "vue";

const {
  class: className,
  asChild = false,
  open = undefined,
  ...props
} = defineProps<Partial<Props> & { class?: string; asChild?: boolean }>();

const service = useMachine(tooltip.machine, {
  ...props,
  positioning: {
    placement: "top",
    offset: { mainAxis: 10 },
  },
  closeDelay: 0,
  openDelay: 0,
  open,
  id: crypto.randomUUID(),
});
const api = computed(() => tooltip.connect(service, normalizeProps));

provide("tooltipApi", api);
</script>

<template>
  <slot />
</template>

// packages/svelte/src/components/ui/tooltip/TooltipRoot.svelte
<script lang="ts">
  import * as tooltip from "@zag-js/tooltip";
  import { useMachine, normalizeProps } from "@zag-js/svelte";
  import { setContext } from "svelte";
  import type { Snippet } from "svelte";

  let {
    disabled,
    children,
    ...props
  }: {
    disabled?: boolean;
    children?: Snippet;
  } & Record<string, any> = $props();

  const service = useMachine(tooltip.machine, () => ({
    ...props,
    disabled,
    id: crypto.randomUUID(),
  }));

  const api = $derived(tooltip.connect(service, normalizeProps));

  setContext("tooltipApi", () => api);
</script>

{@render children?.()}
