// packages/vue/src/components/ui/tooltip/TooltipArrowTip.vue
<script lang="ts" setup>
import { cn } from "@/utils/cn";
import { tooltipArrowTip } from "@midoneui/core/styles/tooltip.styles";
import { Slot } from "@/components/ui/slot";
import type { Api } from "@zag-js/tooltip";
import { inject } from "vue";

const {
  class: className,
  asChild = false,
  ...props
} = defineProps<{
  class?: string;
  asChild?: boolean;
}>();

const api = inject<Api>("tooltipApi");
</script>

<template>
  <Slot
    :class="cn(tooltipArrowTip, className)"
    v-bind="{ ...api?.getArrowTipProps(), ...props, ...$attrs }"
  >
    <slot v-if="asChild" />
    <div v-else>
      <slot />
    </div>
  </Slot>
</template>

// packages/svelte/src/components/ui/tooltip/TooltipArrowTip.svelte
<script lang="ts">
  import { cn } from "@midoneui/core/utils/cn";
  import { tooltipArrowTip } from "@midoneui/core/styles/tooltip.styles";
  import { getContext } from "svelte";

  let {
    class: className,
    ...props
  }: {
    class?: string;
  } & Record<string, any> = $props();

  const getApi = getContext<() => any>("tooltipApi");
  const api = $derived(getApi());
</script>

<div class={cn(tooltipArrowTip, className)} {...api?.getArrowTipProps()} {...props}></div>
