// packages/react/src/components/ui/native-select/index.tsx
import { cn } from "@/utils/cn";
import { input } from "@midoneui/core/styles/input.styles";
import {
  nativeSelect,
  nativeSelectOption,
  NativeSelectOptGroup,
} from "@midoneui/core/styles/native-select.styles";

function NativeSelect({
  children,
  className,
  ...props
}: React.ComponentProps<"select">) {
  return (
    <select className={cn(input, nativeSelect, className)} {...props}>
      {children}
    </select>
  );
}

function NativeSelectOption({
  children,
  className,
  ...props
}: React.ComponentProps<"option">) {
  return (
    <option className={cn(nativeSelectOption, className)} {...props}>
      {children}
    </option>
  );
}

function NativeSelectOptionGroup({
  children,
  className,
  ...props
}: React.ComponentProps<"optgroup">) {
  return (
    <optgroup className={cn(NativeSelectOptGroup, className)} {...props}>
      {children}
    </optgroup>
  );
}

export { NativeSelect, NativeSelectOption, NativeSelectOptionGroup };

// packages/vue/src/components/ui/native-select/NativeSelect.vue
<script lang="ts" setup>
import { cn } from "@/utils/cn";
import { input } from "@midoneui/core/styles/input.styles";
import { nativeSelect } from "@midoneui/core/styles/native-select.styles";

const { class: className, ...props } = defineProps<{
  class?: string;
}>();
</script>

<template>
  <select
    :class="cn(input, nativeSelect, className)"
    v-bind="{ ...props, ...$attrs }"
  >
    <slot />
  </select>
</template>
