// packages/svelte/src/pages/Alert.svelte
<script lang="ts">
  import { AlertRoot, AlertTitle, AlertDescription, AlertCloseTrigger } from "@/components/ui/alert";
</script>

<div class="flex flex-col gap-4 max-w-2xl">
  <AlertRoot variant="primary">
    <AlertTitle>Primary Alert</AlertTitle>
    <AlertDescription>This is a primary alert with a title and description.</AlertDescription>
    <AlertCloseTrigger />
  </AlertRoot>
  <AlertRoot variant="success">
    <AlertTitle>Success</AlertTitle>
    <AlertDescription>Your action was completed successfully.</AlertDescription>
    <AlertCloseTrigger />
  </AlertRoot>
  <AlertRoot variant="danger">
    <AlertTitle>Error</AlertTitle>
    <AlertDescription>Something went wrong. Please try again.</AlertDescription>
    <AlertCloseTrigger />
  </AlertRoot>
  <AlertRoot variant="warning">
    <AlertTitle>Warning</AlertTitle>
    <AlertDescription>Please review the changes before continuing.</AlertDescription>
    <AlertCloseTrigger />
  </AlertRoot>
  <AlertRoot variant="pending">
    <AlertTitle>Pending</AlertTitle>
    <AlertDescription>Your request is being processed.</AlertDescription>
  </AlertRoot>
  <AlertRoot look="outline" variant="primary">
    <AlertTitle>Outline Primary</AlertTitle>
    <AlertDescription>This is an outline alert variant.</AlertDescription>
    <AlertCloseTrigger />
  </AlertRoot>
</div>

// packages/vue/src/pages/Alert.vue
<script lang="ts" setup>
import {
  AlertRoot,
  AlertTitle,
  AlertDescription,
  AlertCloseTrigger,
} from "@/components/ui/alert";
import { Compass } from "lucide-vue-next";
import { Box } from "@/components/ui/box";
</script>

<template>
  <div class="flex flex-col gap-20">
    <div class="grid grid-cols-2">
      <div
        class="justify-center items-center flex gap-2 border-b border-e border-foreground/10 p-5 flex-wrap"
      >
        <AlertRoot variant="primary">
          <Compass />
          <AlertTitle>Success! Your changes have been saved</AlertTitle>
          <AlertDescription>
            This is an alert with icon, title and description.
          </AlertDescription>
          <AlertCloseTrigger />
        </AlertRoot>
        <AlertRoot variant="secondary">
          <Compass />
          <AlertTitle>Success! Your changes have been saved</AlertTitle>
          <AlertDescription>
            This is an alert with icon, title and description.
          </AlertDescription>
          <AlertCloseTrigger />
        </AlertRoot>
        <AlertRoot variant="success">
          <Compass />
          <AlertTitle>Success! Your changes have been saved</AlertTitle>
          <AlertDescription>
            This is an alert with icon, title and description.
          </AlertDescription>
          <AlertCloseTrigger />
        </AlertRoot>
        <AlertRoot variant="danger">
          <Compass />
          <AlertTitle>Success! Your changes have been saved</AlertTitle>
          <AlertDescription>
            This is an alert with icon, title and description.
          </AlertDescription>
          <AlertCloseTrigger />
        </AlertRoot>
        <AlertRoot variant="pending">
          <Compass />
          <AlertTitle>Success! Your changes have been saved</AlertTitle>
          <AlertDescription>
            This is an alert with icon, title and description.
          </AlertDescription>
          <AlertCloseTrigger />
        </AlertRoot>
        <AlertRoot variant="warning">
          <Compass />
          <AlertTitle>Success! Your changes have been saved</AlertTitle>
          <AlertDescription>
            This is an alert with icon, title and description.
          </AlertDescription>
          <AlertCloseTrigger />
        </AlertRoot>
      </div>
      <div
        class="justify-center items-center flex gap-2 border-b border-e border-foreground/10 p-5 flex-wrap"
      >
        <AlertRoot look="filled" variant="primary">
          <Compass />
          <AlertTitle>Success! Your changes have been saved</AlertTitle>
          <AlertDescription>
            This is an alert with icon, title and description.
          </AlertDescription>
          <AlertCloseTrigger />
        </AlertRoot>
        <AlertRoot look="filled" variant="secondary">
          <Compass />
          <AlertTitle>Success! Your changes have been saved</AlertTitle>
          <AlertDescription>
            This is an alert with icon, title and description.
          </AlertDescription>
          <AlertCloseTrigger />
        </AlertRoot>
        <AlertRoot look="filled" variant="success">
          <Compass />
          <AlertTitle>Success! Your changes have been saved</AlertTitle>
          <AlertDescription>
            This is an alert with icon, title and description.
          </AlertDescription>
          <AlertCloseTrigger />
        </AlertRoot>
        <AlertRoot look="filled" variant="danger">
          <Compass />
          <AlertTitle>Success! Your changes have been saved</AlertTitle>
          <AlertDescription>
            This is an alert with icon, title and description.
          </AlertDescription>
          <AlertCloseTrigger />
        </AlertRoot>
        <AlertRoot look="filled" variant="pending">
          <Compass />
          <AlertTitle>Success! Your changes have been saved</AlertTitle>
          <AlertDescription>
            This is an alert with icon, title and description.
          </AlertDescription>
          <AlertCloseTrigger />
        </AlertRoot>
        <AlertRoot look="filled" variant="warning">
          <Compass />
          <AlertTitle>Success! Your changes have been saved</AlertTitle>
          <AlertDescription>
            This is an alert with icon, title and description.
          </AlertDescription>
          <AlertCloseTrigger />
        </AlertRoot>
      </div>
      <div
        class="justify-center items-center flex gap-2 border-b border-e border-foreground/10 p-5 flex-wrap"
      >
        <AlertRoot variant="primary">
          <Compass />
          <AlertTitle>Success! Your changes have been saved</AlertTitle>
          <AlertCloseTrigger />
        </AlertRoot>
        <AlertRoot variant="secondary">
          <Compass />
          <AlertTitle>Success! Your changes have been saved</AlertTitle>
          <AlertCloseTrigger />
        </AlertRoot>
        <AlertRoot variant="success">
          <Compass />
          <AlertTitle>Success! Your changes have been saved</AlertTitle>
          <AlertCloseTrigger />
        </AlertRoot>
        <AlertRoot variant="danger">
          <Compass />
          <AlertTitle>Success! Your changes have been saved</AlertTitle>
          <AlertCloseTrigger />
        </AlertRoot>
        <AlertRoot variant="pending">
          <Compass />
          <AlertTitle>Success! Your changes have been saved</AlertTitle>
          <AlertCloseTrigger />
        </AlertRoot>
        <AlertRoot variant="warning">
          <Compass />
          <AlertTitle>Success! Your changes have been saved</AlertTitle>
          <AlertCloseTrigger />
        </AlertRoot>
      </div>
      <div
        class="justify-center items-center flex gap-2 border-b border-e border-foreground/10 p-5 flex-wrap"
      >
        <AlertRoot look="filled" variant="primary">
          <Compass />
          <AlertTitle>Success! Your changes have been saved</AlertTitle>
        </AlertRoot>
        <AlertRoot look="filled" variant="secondary">
          <Compass />
          <AlertTitle>Success! Your changes have been saved</AlertTitle>
        </AlertRoot>
        <AlertRoot look="filled" variant="success">
          <Compass />
          <AlertTitle>Success! Your changes have been saved</AlertTitle>
        </AlertRoot>
        <AlertRoot look="filled" variant="danger">
          <Compass />
          <AlertTitle>Success! Your changes have been saved</AlertTitle>
        </AlertRoot>
        <AlertRoot look="filled" variant="pending">
          <Compass />
          <AlertTitle>Success! Your changes have been saved</AlertTitle>
        </AlertRoot>
        <AlertRoot look="filled" variant="warning">
          <Compass />
          <AlertTitle>Success! Your changes have been saved</AlertTitle>
        </AlertRoot>
      </div>
      <div
        class="justify-center items-center flex gap-2 border-b border-e border-foreground/10 p-5 flex-wrap"
      >
        <Box class="p-0">
          <AlertRoot variant="ghost">
            <Compass />
            <AlertTitle>Success! Your changes have been saved</AlertTitle>
            <AlertDescription>
              This is an alert with icon, title and description.
            </AlertDescription>
            <AlertCloseTrigger />
          </AlertRoot>
        </Box>
        <Box class="p-0" raised="single">
          <AlertRoot variant="ghost">
            <Compass />
            <AlertTitle>Success! Your changes have been saved</AlertTitle>
            <AlertDescription>
              This is an alert with icon, title and description.
            </AlertDescription>
            <AlertCloseTrigger />
          </AlertRoot>
        </Box>
        <Box class="p-0" raised="double">
          <AlertRoot variant="ghost">
            <Compass />
            <AlertTitle>Success! Your changes have been saved</AlertTitle>
            <AlertDescription>
              This is an alert with icon, title and description.
            </AlertDescription>
            <AlertCloseTrigger />
          </AlertRoot>
        </Box>
      </div>
    </div>
  </div>
</template>
