// packages/react/src/pages/react/chart.tsx
import { Chart, getColor } from "@/components/ui/chart";
import {
  Preview,
  SectionTitle,
  SectionContent,
  InstallPackage,
  PreviewCode,
} from "@/components/docs";

function Main() {
  return (
    <>
      <div id="preview" className="-mt-20">
        <Preview>
          {() => ({
            preview: (
              <>
                <Chart
                  className="max-w-100"
                  config={{
                    type: "bar",
                    data: {
                      labels: [
                        "Jan",
                        "Feb",
                        "Mar",
                        "Apr",
                        "May",
                        "Jun",
                        "Jul",
                        "Aug",
                        "Sep",
                        "Oct",
                        "Nov",
                        "Dec",
                      ],
                      datasets: [
                        {
                          label: "Html Template",
                          maxBarThickness: 12,
                          data: [
                            60, 150, 30, 200, 180, 50, 180, 120, 230, 180, 250,
                            270,
                          ],
                          backgroundColor: () =>
                            getColor("--color-foreground", 0.3),
                          borderColor: () => getColor("--color-foreground"),
                          borderWidth: 1,
                        },
                      ],
                    },
                    options: {
                      maintainAspectRatio: false,
                      plugins: {
                        legend: {
                          display: false,
                        },
                      },
                      scales: {
                        x: {
                          display: false,
                        },
                        y: {
                          display: false,
                        },
                      },
                    },
                  }}
                />
              </>
            ),
            code: (
              <PreviewCode>
                {`
<Chart
  className="max-w-100"
  config={{
    type: "bar",
    data: {
      labels: [
        "Jan",
        "Feb",
        "Mar",
        "Apr",
        "May",
        "Jun",
        "Jul",
        "Aug",
        "Sep",
        "Oct",
        "Nov",
        "Dec",
      ],
      datasets: [
        {
          label: "Html Template",
          maxBarThickness: 12,
          data: [
            60, 150, 30, 200, 180, 50, 180, 120, 230, 180, 250, 270,
          ],
          backgroundColor: () => getColor("--color-foreground", 0.3),
          borderColor: () => getColor("--color-foreground"),
          borderWidth: 1,
        },
      ],
    },
    options: {
      maintainAspectRatio: false,
      plugins: {
        legend: {
          display: false,
        },
      },
      scales: {
        x: {
          display: false,
        },
        y: {
          display: false,
        },
      },
    },
  }}
/>
                `}
              </PreviewCode>
            ),
          })}
        </Preview>
      </div>
      <div id="installation">
        <SectionTitle>Installation</SectionTitle>
        <SectionContent>Install the following dependencies:</SectionContent>
        <InstallPackage>add chart.js</InstallPackage>
        <SectionContent>
          Copy and paste the following code into your project.
        </SectionContent>
        <PreviewCode title="components/ui/chart/index.tsx">
          {`
import ChartJs from "chart.js/auto";
import { useRef, useEffect } from "react";
import { cn } from "@midoneui/core/utils/cn";
import { chart } from "@midoneui/core/styles/chart.styles";
import type { ChartType, ChartConfiguration } from "chart.js";

function getColor(name: string, opacity = 1) {
  const color = getComputedStyle(document.documentElement)
    .getPropertyValue(name)
    .trim();
  if (opacity < 1) {
    return \`color-mix(in oklch, $\{color\} $\{opacity * 100\}%, transparent $\{100 - opacity * 100
            \}%)\`;
  }
  return color;
}

function Chart<TType extends ChartType = ChartType>({
  className,
  config,
  getRef,
  ...props
}: React.ComponentProps<"canvas"> & {
  config: ChartConfiguration<TType>;
  getRef?: (chart: ChartJs<TType>) => void;
}) {
  const chartRef = useRef<
    | (HTMLCanvasElement & {
        instance?: ChartJs<TType>;
      })
    | null
  >(null);

  useEffect(() => {
    if (chartRef.current && !chartRef.current.instance) {
      chartRef.current.instance = new ChartJs(chartRef.current, config);
      getRef?.(chartRef.current.instance);
    }
  }, [config, getRef]);

  return <canvas className={cn(chart, className)} ref={chartRef} {...props} />;
}

export { Chart, getColor };
              `}
        </PreviewCode>
        <SectionContent>
          Update the import paths to match your project setup.
        </SectionContent>
      </div>
      <div id="usage">
        <SectionTitle>Usage</SectionTitle>
        <PreviewCode>
          {`
import { Chart, getColor } from "@/components/ui/chart";
              `}
        </PreviewCode>
        <PreviewCode>
          {`
<Chart
  className="max-w-100"
  config={{
    type: "bar",
    data: {
      labels: [
        "Jan",
        "Feb",
        "Mar",
        "Apr",
        "May",
        "Jun",
        "Jul",
        "Aug",
        "Sep",
        "Oct",
        "Nov",
        "Dec",
      ],
      datasets: [
        {
          label: "Html Template",
          maxBarThickness: 12,
          data: [
            60, 150, 30, 200, 180, 50, 180, 120, 230, 180,
            250, 270,
          ],
          backgroundColor: () =>
            getColor("--color-foreground", 0.3),
          borderColor: () => getColor("--color-foreground"),
          borderWidth: 1,
        },
      ],
    },
    options: {
      maintainAspectRatio: false,
      plugins: {
        legend: {
          display: false,
        },
      },
      scales: {
        x: {
          display: false,
        },
        y: {
          display: false,
        },
      },
    },
  }}
/>
              `}
        </PreviewCode>
      </div>
    </>
  );
}

export default Main;

// packages/vue/src/pages/Chart.vue
<script lang="ts" setup>
import { Chart, getColor } from "@/components/ui/chart";

const chartConfig = {
  type: "bar",
  data: {
    labels: [
      "Jan",
      "Feb",
      "Mar",
      "Apr",
      "May",
      "Jun",
      "Jul",
      "Aug",
      "Sep",
      "Oct",
      "Nov",
      "Dec",
    ],
    datasets: [
      {
        label: "Html Template",
        maxBarThickness: 12,
        data: [
          60, 150, 30, 200, 180, 50, 180, 120, 230, 180, 250, 270,
        ],
        backgroundColor: () => getColor("--color-foreground", 0.3),
        borderColor: () => getColor("--color-foreground"),
        borderWidth: 1,
      },
    ],
  },
  options: {
    maintainAspectRatio: false,
    plugins: {
      legend: {
        display: false,
      },
    },
    scales: {
      x: {
        display: false,
      },
      y: {
        display: false,
      },
    },
  },
};
</script>

<template>
  <div class="flex flex-col gap-20">
    <div class="grid grid-cols-2">
      <div class="justify-center items-center flex gap-2 border-b border-e border-foreground/10 p-5 flex-wrap">
        <Chart
          class="max-w-100"
          :config="chartConfig"
        />
      </div>
    </div>
  </div>
</template>
