// packages/svelte/src/pages/Input.svelte
<script lang="ts">
  import { Input } from "@/components/ui/input";
  import { Label } from "@/components/ui/label";
</script>

<div class="flex flex-col gap-6 max-w-md">
  <div class="flex flex-col gap-2">
    <Label>Default Input</Label>
    <Input placeholder="Enter text..." />
  </div>
  <div class="flex flex-col gap-2">
    <Label>Email</Label>
    <Input type="email" placeholder="you@example.com" />
  </div>
  <div class="flex flex-col gap-2">
    <Label>Password</Label>
    <Input type="password" placeholder="••••••••" />
  </div>
  <div class="flex flex-col gap-2">
    <Label>Disabled</Label>
    <Input disabled placeholder="Disabled input" />
  </div>
</div>

// packages/vue/src/pages/Input.vue
<script lang="ts" setup>
import { Input } from "@/components/ui/input";
</script>

<template>
  <div class="flex flex-col gap-20">
    <div class="grid grid-cols-2">
      <div class="justify-center items-center flex gap-2 border-b border-e border-foreground/10 p-5 flex-wrap">
        <Input type="email" placeholder="Email" />
      </div>
    </div>
  </div>
</template>
