// packages/svelte/src/components/ui/alert/AlertCloseTrigger.svelte
<script lang="ts">
  import { X } from "lucide-svelte";
  import { cn } from "@midoneui/core/utils/cn";
  import { alertCloseTrigger } from "@midoneui/core/styles/alert.styles";
  import { getContext } from "svelte";
  import type { Snippet } from "svelte";

  let {
    class: className,
    children,
    ...props
  }: { class?: string; children?: Snippet } & Record<string, any> = $props();

  const context = getContext<{ getPresent: () => boolean; setPresent: (v: boolean) => void } | null>("alertPresent");
</script>

<div
  class={cn(alertCloseTrigger, className)}
  {...props}
  role="button"
  tabindex="0"
  onclick={() => context?.setPresent(false)}
  onkeydown={(e) => { if (e.key === 'Enter' || e.key === ' ') context?.setPresent(false); }}
>
  {#if children}
    {@render children()}
  {:else}
    <X />
  {/if}
</div>

// packages/vue/src/components/ui/alert/AlertCloseTrigger.vue
<script lang="ts" setup>
import { X } from "lucide-vue-next";
import { cn } from "@midoneui/core/utils/cn";
import { alertCloseTrigger } from "@midoneui/core/styles/alert.styles";
import { inject } from "vue";

const props = defineProps<{
  class?: string;
}>();

const context = inject<{ present: any; setPresent: (value: boolean) => void } | null>("alertPresent", null);
</script>

<template>
  <div
    v-if="!$slots.default"
    :class="cn([props.class, alertCloseTrigger])"
    v-bind="props"
    @click="context?.setPresent(false)"
  >
    <X />
  </div>
  <div v-else :class="cn([props.class, alertCloseTrigger])" v-bind="props">
    <slot />
  </div>
</template>
