// packages/react/src/components/ui/progress-linear/index.tsx
import { cn } from "@midoneui/core/utils/cn";
import { Label } from "@/components/ui/label";
import {
  progressRoot,
  progressLabel,
  progressValueText,
  progressTrack,
  progressRange,
} from "@midoneui/core/styles/progress-linear.styles";
import * as progress from "@zag-js/progress";
import { useMachine, normalizeProps } from "@zag-js/react";
import type { Api, Props } from "@zag-js/progress";
import { Slot } from "@/components/ui/slot";
import { createContext, useContext, useId } from "react";

const ApiContext = createContext<Api | null>(null);

export function ProgressRoot({
  children,
  className,
  asChild = false,
  ...props
}: React.ComponentProps<"div"> & Partial<Props> & { asChild?: boolean }) {
  const service = useMachine(progress.machine, { id: useId() });
  const api = progress.connect(service, normalizeProps);

  return (
    <ApiContext.Provider value={api}>
      <Slot
        className={cn(progressRoot, className)}
        {...api?.getRootProps()}
        {...props}
      >
        {asChild ? children : <div>{children}</div>}
      </Slot>
    </ApiContext.Provider>
  );
}

export function ProgressLabel({
  children,
  className,
  asChild = false,
  ...props
}: React.ComponentProps<"label"> & {
  asChild?: boolean;
}) {
  const api = useContext(ApiContext);

  return (
    <Slot {...api?.getLabelProps()} {...props}>
      {!asChild ? (
        <Label className={cn(progressLabel, className)}>{children}</Label>
      ) : (
        children
      )}
    </Slot>
  );
}

export function ProgressValueText({
  className,
  ...props
}: React.ComponentProps<"div">) {
  const api = useContext(ApiContext);

  return (
    <div
      className={cn(progressValueText, className)}
      {...api?.getValueTextProps()}
      {...props}
    >
      {api?.valueAsString}
    </div>
  );
}

export function ProgressTrack({
  children,
  className,
  ...props
}: React.ComponentProps<"div">) {
  const api = useContext(ApiContext);

  return (
    <div
      className={cn(progressTrack, className)}
      {...api?.getTrackProps()}
      {...props}
    >
      {children}
    </div>
  );
}

export function ProgressRange({
  className,
  ...props
}: React.ComponentProps<"div">) {
  const api = useContext(ApiContext);

  return (
    <div
      className={cn(progressRange, className)}
      {...api?.getRangeProps()}
      {...props}
    />
  );
}

// packages/svelte/src/components/ui/progress-linear/ProgressLinear.svelte
<script lang="ts">
  import * as progress from "@zag-js/progress";
  import { useMachine, normalizeProps } from "@zag-js/svelte";
  import { cn } from "@midoneui/core/utils/cn";
  import { progressTrack, progressRange } from "@midoneui/core/styles/progress-linear.styles";

  let {
    class: className,
    value = 50,
    ...props
  }: { class?: string; value?: number } & Record<string, any> = $props();

  const service = useMachine(progress.machine, () => ({ ...props, value, id: crypto.randomUUID() }));
  const api = $derived(progress.connect(service, normalizeProps));
</script>

<div class={cn("w-full flex flex-col gap-2", className)} {...api.getRootProps()}>
  <div class={cn(progressTrack)} {...api.getTrackProps()}>
    <div class={cn(progressRange)} {...api.getRangeProps()}></div>
  </div>
</div>
