// packages/svelte/src/components/ui/avatar/AvatarImage.svelte
<script lang="ts">
  import { cn } from "@midoneui/core/utils/cn";
  import { avatarImage } from "@midoneui/core/styles/avatar.styles";
  import { getContext } from "svelte";

  let { class: className, ...props }: { class?: string } & Record<string, any> = $props();
  const getApi = getContext<() => any>("avatarApi");
  const api = $derived(getApi());
</script>

<img class={cn(avatarImage, className)} {...api?.getImageProps()} {...props} alt="" />

// packages/vue/src/components/ui/avatar/AvatarImage.vue
<script lang="ts" setup>
import { cn } from "@/utils/cn";
import { avatarImage } from "@midoneui/core/styles/avatar.styles";
import { inject } from "vue";
import type { Api } from "@zag-js/avatar";

const { class: className, ...props } = defineProps<{
  class?: string;
}>();

const api = inject<Api>("avatarApi");
</script>

<template>
  <img
    :class="cn(avatarImage, className)"
    v-bind="{ ...props, ...$attrs, ...api?.getImageProps() }"
  />
</template>
