// packages/svelte/src/pages/Avatar.svelte
<script lang="ts">
  import { AvatarRoot, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
</script>

<div class="flex flex-wrap gap-4">
  <AvatarRoot>
    <AvatarImage src="https://images.unsplash.com/photo-1492633423870-43d1cd2775eb?w=128&h=128&fit=crop&crop=face" />
    <AvatarFallback>JD</AvatarFallback>
  </AvatarRoot>
  <AvatarRoot bordered>
    <AvatarImage src="https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=128&h=128&fit=crop&crop=face" />
    <AvatarFallback>SM</AvatarFallback>
  </AvatarRoot>
  <AvatarRoot>
    <AvatarFallback>AB</AvatarFallback>
  </AvatarRoot>
</div>

// packages/react/src/pages/avatar.tsx
import {
  AvatarRoot,
  AvatarFallback,
  AvatarImage,
} from "@/components/ui/avatar";

function Main() {
  return (
    <div className="flex flex-col gap-20">
      <div className="grid grid-cols-2">
        <div className="justify-center items-center flex gap-2 border-b border-e border-foreground/10 p-5 flex-wrap">
          <AvatarRoot>
            <AvatarFallback>PA</AvatarFallback>
            <AvatarImage src="https://i.pravatar.cc/300" alt="avatar" />
          </AvatarRoot>
        </div>
        <div className="justify-center items-center flex gap-2 border-b border-e border-foreground/10 p-5 flex-wrap">
          <AvatarRoot bordered={false}>
            <AvatarFallback>PA</AvatarFallback>
            <AvatarImage src="https://i.pravatar.cc/300" alt="avatar" />
          </AvatarRoot>
        </div>
        <div className="justify-center items-center flex gap-2 border-b border-e border-foreground/10 p-5 flex-wrap">
          <AvatarRoot className="rounded-full">
            <AvatarFallback>PA</AvatarFallback>
            <AvatarImage src="https://i.pravatar.cc/300" alt="avatar" />
          </AvatarRoot>
        </div>
        <div className="justify-center items-center flex gap-2 border-b border-e border-foreground/10 p-5 flex-wrap">
          <AvatarRoot className="rounded-full" bordered={false}>
            <AvatarFallback>PA</AvatarFallback>
            <AvatarImage src="https://i.pravatar.cc/300" alt="avatar" />
          </AvatarRoot>
        </div>
      </div>
    </div>
  );
}

export default Main;
