// packages/react/src/pages/vue/toast.tsx
import { Button } from "@/components/ui/button";
import {
  toaster,
  ToasterContainer,
  ToastRoot,
  ToastTitle,
  ToastDescription,
  ToastCloseTrigger,
} from "@/components/ui/toast";
import {
  Preview,
  SectionTitle,
  SectionContent,
  InstallPackage,
  PreviewCode,
} from "@/components/docs";

function Main() {
  return (
    <>
      <div id="preview" className="-mt-20">
        <Preview>
          {() => ({
            preview: (
              <>
                <Button
                  onClick={() =>
                    toaster.create({
                      title: "Event has been created",
                      description: "Sunday, December 03, 2023 at 9:00 AM",
                      type: "info",
                    })
                  }
                >
                  Show Toast
                </Button>
                <ToasterContainer toaster={toaster}>
                  {(toast) => (
                    <ToastRoot key={toast.id}>
                      <ToastTitle>{toast.title}</ToastTitle>
                      <ToastDescription>{toast.description}</ToastDescription>
                      <ToastCloseTrigger />
                    </ToastRoot>
                  )}
                </ToasterContainer>
              </>
            ),
            code: (
              <PreviewCode>
                {`
<Button
  @click="
    () =>
      toaster.create({
        title: 'Event has been created',
        description: 'Sunday, December 03, 2023 at 9:00 AM',
        type: 'info',
      })
  "
>
  Show Toast
</Button>
<ToasterContainer :toaster="toaster" v-slot="{ toast }">
  <ToastRoot :key="toast.id">
    <ToastTitle>{{ toast.title }}</ToastTitle>
    <ToastDescription>
      {{ toast.description }}
    </ToastDescription>
    <ToastCloseTrigger />
  </ToastRoot>
</ToasterContainer>
                `}
              </PreviewCode>
            ),
          })}
        </Preview>
      </div>
      <div id="installation">
        <SectionTitle>Installation</SectionTitle>
        <SectionContent>Install the following dependencies:</SectionContent>
        <InstallPackage>add @zag-js/vue @zag-js/toast</InstallPackage>
        <SectionContent>
          Copy and paste the following code into your project.
        </SectionContent>
        <PreviewCode title="components/ui/toast/toaster.ts">
          {`
import * as toast from "@zag-js/toast";

const toaster = toast.createStore({
  placement: "bottom-end",
  overlap: true,
  gap: 24,
});

export default toaster;
            `}
        </PreviewCode>
        <PreviewCode title="components/ui/toast/ToastRoot.vue">
          {`
<script lang="ts" setup>
import { cn } from "@midoneui/core/utils/cn";
import { toastRoot } from "@midoneui/core/styles/toast.styles";
import {
  boxVariants,
  type BoxVariants,
} from "@midoneui/core/styles/box.styles";
import { Slot } from "@/components/ui/slot";
import type { Api } from "@zag-js/toast";
import { inject } from "vue";

const {
  class: className,
  asChild = false,
  raised = "single",
  ...props
} = defineProps<
  BoxVariants & {
    class?: string;
    asChild?: boolean;
  }
>();

const api = inject<Api>("toastApi");
</script>

<template>
  <Slot
    :class="cn([boxVariants({ raised, className }), toastRoot, className])"
    v-bind="{ ...api?.getRootProps(), ...props, ...$attrs }"
  >
    <slot v-if="asChild" />
    <div v-else>
      <span v-bind="{ ...api?.getGhostBeforeProps() }" />
      <div data-scope="toast" data-part="progressbar" />
      <slot />
      <span v-bind="{ ...api?.getGhostAfterProps() }" />
    </div>
  </Slot>
</template>
            `}
        </PreviewCode>
        <PreviewCode title="components/ui/toast/ToastTitle.vue">
          {`
<script lang="ts" setup>
import { cn } from "@midoneui/core/utils/cn";
import { toastTitle } from "@midoneui/core/styles/toast.styles";
import { Slot } from "@/components/ui/slot";
import type { Api } from "@zag-js/toast";
import { inject } from "vue";

const {
  class: className,
  asChild = false,
  ...props
} = defineProps<{
  class?: string;
  asChild?: boolean;
}>();

const api = inject<Api>("toastApi");
</script>

<template>
  <Slot
    :class="cn(toastTitle, className)"
    v-bind="{ ...api?.getTitleProps(), ...props, ...$attrs }"
  >
    <slot v-if="asChild" />
    <div v-else>
      <slot />
    </div>
  </Slot>
</template>
            `}
        </PreviewCode>
        <PreviewCode title="components/ui/toast/ToastDescription.vue">
          {`
<script lang="ts" setup>
import { cn } from "@midoneui/core/utils/cn";
import { toastDescription } from "@midoneui/core/styles/toast.styles";
import { Slot } from "@/components/ui/slot";
import type { Api } from "@zag-js/toast";
import { inject } from "vue";

const {
  class: className,
  asChild = false,
  ...props
} = defineProps<{
  class?: string;
  asChild?: boolean;
}>();

const api = inject<Api>("toastApi");
</script>

<template>
  <Slot
    :class="cn(toastDescription, className)"
    v-bind="{ ...api?.getDescriptionProps(), ...props, ...$attrs }"
  >
    <slot v-if="asChild" />
    <div v-else>
      <slot />
    </div>
  </Slot>
</template>
            `}
        </PreviewCode>
        <PreviewCode title="components/ui/toast/ToastCloseTrigger.vue">
          {`
<script lang="ts" setup>
import { cn } from "@midoneui/core/utils/cn";
import { toastCloseTrigger } from "@midoneui/core/styles/toast.styles";
import {
  buttonVariants,
  type ButtonVariants,
} from "@midoneui/core/styles/button.styles";
import { Slot } from "@/components/ui/slot";
import { Button } from "@/components/ui/button";
import { X } from "lucide-vue-next";
import type { Api } from "@zag-js/toast";
import { inject } from "vue";

const {
  class: className,
  asChild = false,
  look = "outline",
  variant = "secondary",
  size,
  ...props
} = defineProps<
  ButtonVariants & {
    class?: string;
    asChild?: boolean;
  }
>();

const api = inject<Api>("toastApi");
</script>

<template>
  <Slot v-bind="{ ...api?.getCloseTriggerProps(), ...props, ...$attrs }">
    <Button
      variant="ghost"
      v-if="!$slots.default"
      :class="cn(toastCloseTrigger, className)"
      v-bind="{ ...props }"
    >
      <X class="size-4" />
    </Button>
    <template v-else>
      <slot v-if="asChild" />
      <Button
        v-else
        :class="
          cn(buttonVariants({ look, variant, size, className }), className)
        "
      >
        <slot />
      </Button>
    </template>
  </Slot>
</template>
            `}
        </PreviewCode>
        <PreviewCode title="components/ui/toast/ToastItem.vue">
          {`
<script lang="ts" setup>
import * as toast from "@zag-js/toast";
import { provide, computed } from "vue";
import { useMachine, normalizeProps } from "@zag-js/vue";

const { toastGroup, serviceGroup, index } = defineProps<{
  class?: string;
  asChild?: boolean;
  toastGroup: toast.Options;
  serviceGroup: toast.GroupService;
  index: number;
}>();

const composedProps = computed(() => ({
  ...toastGroup,
  index,
  parent: serviceGroup,
}));
const service = useMachine(toast.machine, composedProps);
const api = toast.connect(service, normalizeProps);

provide("toastApi", api);
</script>

<template>
  <slot
    :toast="{
      ...api,
      id: toastGroup.id,
    }"
  />
</template>
            `}
        </PreviewCode>
        <PreviewCode title="components/ui/toast/ToasterContainer.vue">
          {`
<script lang="ts" setup>
import { cn } from "@midoneui/core/utils/cn";
import * as toast from "@zag-js/toast";
import { toasterContainer } from "@midoneui/core/styles/toast.styles";
import type { Store } from "@zag-js/toast";
import { normalizeProps, useMachine } from "@zag-js/vue";
import { computed } from "vue";
import { ToastItem } from ".";

const {
  class: className,
  asChild = false,
  toaster,
  ...props
} = defineProps<{ class?: string; asChild?: boolean; toaster: Store }>();

const serviceGroup = useMachine(toast.group.machine, {
  id: crypto.randomUUID(),
  store: toaster,
});
const apiGroup = computed(() =>
  toast.group.connect(serviceGroup, normalizeProps)
);
</script>

<template>
  <Teleport to="body">
    <div
      :class="cn(toasterContainer, className)"
      v-bind="{ ...apiGroup?.getGroupProps(), ...props, ...$attrs }"
    >
      <ToastItem
        v-for="(toastGroup, index) in apiGroup.getToasts()"
        :key="toastGroup.id"
        :index="index"
        :toastGroup="toastGroup"
        :serviceGroup="serviceGroup"
        v-slot="{ toast }"
      >
        <slot :toast="toast" />
      </ToastItem>
    </div>
  </Teleport>
</template>
            `}
        </PreviewCode>
        <PreviewCode title="components/ui/toast/index.ts">
          {`
export { default as toaster } from "./toaster";
export { default as ToastRoot } from "./ToastRoot.vue";
export { default as ToastTitle } from "./ToastTitle.vue";
export { default as ToastDescription } from "./ToastDescription.vue";
export { default as ToastCloseTrigger } from "./ToastCloseTrigger.vue";
export { default as ToastItem } from "./ToastItem.vue";
export { default as ToasterContainer } from "./ToasterContainer.vue";
              `}
        </PreviewCode>
        <SectionContent>
          Update the import paths to match your project setup.
        </SectionContent>
      </div>
      <div id="usage">
        <SectionTitle>Usage</SectionTitle>
        <PreviewCode>
          {`
import {
  toaster,
  ToasterContainer,
  ToastRoot,
  ToastTitle,
  ToastDescription,
  ToastCloseTrigger,
} from "@/components/ui/toast";
              `}
        </PreviewCode>
        <PreviewCode>
          {`
<Button
  @click="
    () =>
      toaster.create({
        title: 'Event has been created',
        description: 'Sunday, December 03, 2023 at 9:00 AM',
        type: 'info',
      })
  "
>
  Show Toast
</Button>
<ToasterContainer :toaster="toaster" v-slot="{ toast }">
  <ToastRoot :key="toast.id">
    <ToastTitle>{{ toast.title }}</ToastTitle>
    <ToastDescription>
      {{ toast.description }}
    </ToastDescription>
    <ToastCloseTrigger />
  </ToastRoot>
</ToasterContainer>
              `}
        </PreviewCode>
      </div>
    </>
  );
}

export default Main;

// packages/react/src/pages/toast.tsx
import { MoveUpRight } from "lucide-react";
import { Button } from "@/components/ui/button";
import {
  toaster,
  ToasterContainer,
  ToastRoot,
  ToastTitle,
  ToastDescription,
  ToastCloseTrigger,
} from "@/components/ui/toast";
import {
  Wrapper,
  Title,
  Subtitle,
  Menu,
  Preview,
  SectionTitle,
  SectionContent,
  InstallPackage,
  PreviewCode,
  ApiButton,
} from "@/components/docs";

function Main() {
  return (
    <>
      <Wrapper>
        <div className="flex flex-col gap-20">
          <div>
            <Title>Toast</Title>
            <Subtitle>
              A small notification that pops up briefly to share quick updates
              or alerts without interrupting the user.
            </Subtitle>
            <div className="flex gap-3 mt-5">
              <ApiButton
                target="_blank"
                href="https://zagjs.com/components/react/toast"
              >
                Docs <MoveUpRight className="stroke-1 size-3" />
              </ApiButton>
              <ApiButton
                target="_blank"
                href="https://zagjs.com/components/react/toast#methods-and-properties"
              >
                Api Reference <MoveUpRight className="stroke-1 size-3" />
              </ApiButton>
            </div>
            <Preview>
              {() => ({
                preview: (
                  <>
                    <Button
                      onClick={() =>
                        toaster.create({
                          title: "Event has been created",
                          description: "Sunday, December 03, 2023 at 9:00 AM",
                          type: "info",
                        })
                      }
                    >
                      Show Toast
                    </Button>
                    <ToasterContainer toaster={toaster}>
                      {(toast) => (
                        <ToastRoot key={toast.id}>
                          <ToastTitle>{toast.title}</ToastTitle>
                          <ToastDescription>
                            {toast.description}
                          </ToastDescription>
                          <ToastCloseTrigger />
                        </ToastRoot>
                      )}
                    </ToasterContainer>
                  </>
                ),
                code: (
                  <PreviewCode>
                    {`
<Button
  onClick={() =>
    toaster.create({
      title: "Event has been created",
      description: "Sunday, December 03, 2023 at 9:00 AM",
      type: "info",
    })
  }
>
  Show Toast
</Button>
<ToasterContainer toaster={toaster}>
  {(toast) => (
    <ToastRoot key={toast.id}>
      <ToastTitle>{toast.title}</ToastTitle>
      <ToastDescription>{toast.description}</ToastDescription>
      <ToastCloseTrigger />
    </ToastRoot>
  )}
</ToasterContainer>
                `}
                  </PreviewCode>
                ),
              })}
            </Preview>
          </div>
          <div id="installation">
            <SectionTitle>Installation</SectionTitle>
            <SectionContent>Install the following dependencies:</SectionContent>
            <InstallPackage>add @zag-js/react @zag-js/toast</InstallPackage>
            <SectionContent>
              Copy and paste the following code into your project.
            </SectionContent>
            <PreviewCode title="components/ui/toast/index.tsx">
              {`
import { cn } from "@midoneui/core/utils/cn";
import {
  toastRoot,
  toastTitle,
  toastDescription,
  toastCloseTrigger,
  toasterContainer,
} from "@midoneui/core/styles/toast.styles";
import { Button } from "@/components/ui/button";
import {
  buttonVariants,
  type ButtonVariants,
} from "@midoneui/core/styles/button.styles";
import {
  boxVariants,
  type BoxVariants,
} from "@midoneui/core/styles/box.styles";
import { X } from "lucide-react";
import * as toast from "@zag-js/toast";
import { useMachine, normalizeProps, Portal } from "@zag-js/react";
import type { Api, Store } from "@zag-js/toast";
import { Slot } from "@/components/ui/slot";
import { createContext, useContext, useId } from "react";

const ApiContext = createContext<Api | null>(null);

export const toaster = toast.createStore({
  placement: "bottom-end",
  overlap: true,
  gap: 24,
});

export function ToastRoot({
  children,
  className,
  asChild = false,
  filled,
  variant,
  raised = "single",
  ...props
}: React.ComponentProps<"div"> & BoxVariants & { asChild?: boolean }) {
  const api = useContext(ApiContext);

  return (
    <Slot
      className={cn([
        boxVariants({ filled, variant, raised, className }),
        toastRoot,
        className,
      ])}
      {...api?.getRootProps()}
      {...props}
    >
      {asChild ? (
        children
      ) : (
        <div>
          <span {...api?.getGhostBeforeProps()} />
          <div data-scope="toast" data-part="progressbar" />
          {children}
          <span {...api?.getGhostAfterProps()} />
        </div>
      )}
    </Slot>
  );
}

export function ToastTitle({
  children,
  className,
  asChild = false,
  ...props
}: React.ComponentProps<"div"> & { asChild?: boolean }) {
  const api = useContext(ApiContext);

  return (
    <Slot
      className={cn(toastTitle, className)}
      {...api?.getTitleProps()}
      {...props}
    >
      {asChild ? children : <div>{children}</div>}
    </Slot>
  );
}

export function ToastDescription({
  children,
  className,
  asChild = false,
  ...props
}: React.ComponentProps<"div"> & { asChild?: boolean }) {
  const api = useContext(ApiContext);

  return (
    <Slot
      className={cn(toastDescription, className)}
      {...api?.getDescriptionProps()}
      {...props}
    >
      {asChild ? children : <div>{children}</div>}
    </Slot>
  );
}

export function ToastCloseTrigger({
  children,
  className,
  filled,
  variant,
  size,
  asChild,
  ...props
}: React.ComponentProps<"button"> & ButtonVariants & { asChild?: boolean }) {
  const api = useContext(ApiContext);

  return (
    <Slot {...api?.getCloseTriggerProps()} {...props}>
      {!children ? (
        <Button className={cn(toastCloseTrigger, className)} {...props}>
          <X className="size-4" />
        </Button>
      ) : asChild ? (
        children
      ) : (
        <Button
          className={cn(
            buttonVariants({ filled, variant, size, className }),
            className
          )}
        >
          {children}
        </Button>
      )}
    </Slot>
  );
}

export function ToastItem({
  toastGroup,
  serviceGroup,
  index,
  children,
}: {
  toastGroup: toast.Options<React.ReactNode>;
  serviceGroup: toast.GroupService;
  index: number;
  children: (api: Api & { id?: string }) => React.ReactNode;
}) {
  const composedProps = { ...toastGroup, index, parent: serviceGroup };
  const service = useMachine(toast.machine, composedProps);
  const api = toast.connect(service, normalizeProps);

  return (
    <ApiContext.Provider value={api}>
      {children({
        ...api,
        id: toastGroup.id,
      })}
    </ApiContext.Provider>
  );
}

export function ToasterContainer({
  className,
  children,
  toaster,
}: {
  className?: string;
  children: (api: Api & { id?: string }) => React.ReactNode;
  toaster: Store;
}) {
  const serviceGroup = useMachine(toast.group.machine, {
    id: useId(),
    store: toaster,
  });
  const apiGroup = toast.group.connect(serviceGroup, normalizeProps);

  return (
    <Portal>
      <div
        className={cn(toasterContainer, className)}
        {...apiGroup.getGroupProps()}
      >
        {apiGroup.getToasts().map((toastGroup, index) => {
          return (
            <ToastItem
              key={toastGroup.id}
              index={index}
              toastGroup={toastGroup}
              serviceGroup={serviceGroup}
            >
              {children}
            </ToastItem>
          );
        })}
      </div>
    </Portal>
  );
}
              `}
            </PreviewCode>
            <SectionContent>
              Update the import paths to match your project setup.
            </SectionContent>
          </div>
          <div id="usage">
            <SectionTitle>Usage</SectionTitle>
            <PreviewCode>
              {`
import {
  toaster,
  ToasterContainer,
  ToastRoot,
  ToastTitle,
  ToastDescription,
  ToastCloseTrigger,
} from "@/components/ui/toast";
              `}
            </PreviewCode>
            <PreviewCode>
              {`
<Button
  onClick={() =>
    toaster.create({
      title: "Event has been created",
      description: "Sunday, December 03, 2023 at 9:00 AM",
      type: "info",
    })
  }
>
  Show Toast
</Button>
<ToasterContainer toaster={toaster}>
  {(toast) => (
    <ToastRoot key={toast.id}>
      <ToastTitle>{toast.title}</ToastTitle>
      <ToastDescription>
        {toast.description}
      </ToastDescription>
      <ToastCloseTrigger />
    </ToastRoot>
  )}
</ToasterContainer>
              `}
            </PreviewCode>
          </div>
        </div>
      </Wrapper>
      <Menu>
        <a className="hover:text-foreground py-1.5" href="#installation">
          Installation
        </a>
        <a className="hover:text-foreground py-1.5" href="#usage">
          Usage
        </a>
      </Menu>
    </>
  );
}

export default Main;
