// packages/svelte/src/pages/Tooltip.svelte
<script lang="ts">
  import { TooltipRoot, TooltipTrigger, TooltipPositioner, TooltipContent } from "@/components/ui/tooltip";
  import { Button } from "@/components/ui/button";
</script>

<div class="flex gap-4 items-center">
  <TooltipRoot>
    <TooltipTrigger>
      <Button variant="primary">Hover me</Button>
    </TooltipTrigger>
    <TooltipPositioner>
      <TooltipContent>This is a tooltip!</TooltipContent>
    </TooltipPositioner>
  </TooltipRoot>
  <TooltipRoot>
    <TooltipTrigger>
      <Button variant="secondary" look="outline">Another tooltip</Button>
    </TooltipTrigger>
    <TooltipPositioner>
      <TooltipContent>Here's more information</TooltipContent>
    </TooltipPositioner>
  </TooltipRoot>
</div>

// packages/react/src/pages/tooltip.tsx
import {
  TooltipRoot,
  TooltipTrigger,
  TooltipPositioner,
  TooltipContent,
} from "@/components/ui/tooltip";

function Main() {
  return (
    <div className="flex flex-col gap-20">
      <div className="grid grid-cols-2">
        <div className="justify-center items-center flex gap-2 border-b border-e border-foreground/10 p-5 flex-wrap">
          <TooltipRoot>
            <TooltipTrigger>Hover Me</TooltipTrigger>
            <TooltipPositioner>
              <TooltipContent>I am a tooltip!</TooltipContent>
            </TooltipPositioner>
          </TooltipRoot>
        </div>
      </div>
    </div>
  );
}

export default Main;
