// packages/vue/src/components/ui/input/Input.vue
<script lang="ts" setup>
import { cn } from "@/utils/cn";
import { input } from "@midoneui/core/styles/input.styles";

const {
  class: className,
  type,
  ...props
} = defineProps<{
  class?: string;
  type?: string;
}>();
</script>

<template>
  <input :type="type" :class="cn(input, className)" v-bind="{ ...props }" />
</template>

// packages/docs/src/components/ui/input/index.tsx
import { cn } from "@midoneui/core/utils/cn";
import { input } from "@midoneui/core/styles/input.styles";

function Input({
  className,
  children,
  type,
  ...props
}: React.ComponentProps<"input">) {
  return <input type={type} className={cn(input, className)} {...props} />;
}

export { Input };
