// packages/svelte/src/components/ui/input/Input.svelte
<script lang="ts">
  import { cn } from "@midoneui/core/utils/cn";
  import { input } from "@midoneui/core/styles/input.styles";
  import type { HTMLInputAttributes } from "svelte/elements";

  let {
    class: className,
    type,
    ...props
  }: {
    class?: string;
    type?: string;
  } & HTMLInputAttributes = $props();
</script>

<input {type} class={cn(input, className)} {...props} />

// packages/docs/src/components/ui/input/index.tsx
import { cn } from "@midoneui/core/utils/cn";
import { input } from "@midoneui/core/styles/input.styles";

function Input({
  className,
  children,
  type,
  ...props
}: React.ComponentProps<"input">) {
  return <input type={type} className={cn(input, className)} {...props} />;
}

export { Input };
