// packages/svelte/src/components/ui/table/TableBody.svelte
<script lang="ts">
  import { cn } from "@midoneui/core/utils/cn";
  import { tableBody } from "@midoneui/core/styles/table.styles";
  import type { Snippet } from "svelte";

  let { class: className, children, ...props }: { class?: string; children?: Snippet } & Record<string, any> = $props();
</script>

<tbody class={cn(tableBody, className)} {...props}>
  {@render children?.()}
</tbody>

// packages/vue/src/components/ui/table/TableBody.vue
<script lang="ts" setup>
import { cn } from "@midoneui/core/utils/cn";
import { tableBody } from "@midoneui/core/styles/table.styles";

const props = defineProps<{
  class?: string;
}>();
</script>

<template>
  <tbody :class="cn(tableBody, props.class)" v-bind="props">
    <slot />
  </tbody>
</template>
