// packages/svelte/src/components/ui/table/TableRow.svelte
<script lang="ts">
  import { cn } from "@midoneui/core/utils/cn";
  import { tableRow } from "@midoneui/core/styles/table.styles";
  import type { Snippet } from "svelte";

  let { class: className, children, ...props }: { class?: string; children?: Snippet } & Record<string, any> = $props();
</script>

<tr class={cn(tableRow, className)} {...props}>
  {@render children?.()}
</tr>

// packages/vue/src/components/ui/table/TableRow.vue
<script lang="ts" setup>
import { cn } from "@/utils/cn";
import { tableRow } from "@midoneui/core/styles/table.styles";

const { class: className, ...props } = defineProps<{
  class?: string;
}>();
</script>

<template>
  <tr :class="cn(tableRow, className)" v-bind="{ ...props }">
    <slot />
  </tr>
</template>
