// packages/svelte/src/components/ui/table/TableCell.svelte
<script lang="ts">
  import { cn } from "@midoneui/core/utils/cn";
  import { tableCellVariants, type TableCellVariants } from "@midoneui/core/styles/table.styles";
  import type { Snippet } from "svelte";

  let {
    class: className,
    variant,
    raised,
    children,
    ...props
  }: TableCellVariants & { class?: string; children?: Snippet } & Record<string, any> = $props();
</script>

<td class={cn(tableCellVariants({ variant, raised }), className)} {...props}>
  {@render children?.()}
</td>

// packages/vue/src/components/ui/table/TableCell.vue
<script lang="ts" setup>
import { cn } from "@midoneui/core/utils/cn";
import { tableCellVariants } from "@midoneui/core/styles/table.styles";
import { inject } from "vue";

const props = defineProps<{
  class?: string;
}>();

const variant = inject<
  | {
      variant?: "default" | "boxed" | null;
      raised?: "single" | "double" | null;
    }
  | undefined
>("tableVariant", undefined);
</script>

<template>
  <td
    :class="
      cn(tableCellVariants({ ...variant, className: props.class }), props.class)
    "
    v-bind="props"
  >
    <slot />
  </td>
</template>
