// packages/svelte/src/components/ui/table/Table.svelte
<script lang="ts">
  import { cn } from "@midoneui/core/utils/cn";
  import { tableContainer, tableVariants, type TableVariants } from "@midoneui/core/styles/table.styles";
  import type { Snippet } from "svelte";

  let {
    class: className,
    variant,
    raised,
    children,
    ...props
  }: TableVariants & { class?: string; children?: Snippet } & Record<string, any> = $props();
</script>

<div class={cn(tableContainer)}>
  <table class={cn(tableVariants({ variant, raised }), className)} {...props}>
    {@render children?.()}
  </table>
</div>

// packages/vue/src/components/ui/table/Table.vue
<script lang="ts" setup>
import { cn } from "@midoneui/core/utils/cn";
import {
  tableVariants,
  type TableVariants,
} from "@midoneui/core/styles/table.styles";
import { provide, computed } from "vue";
import TableContainer from "./TableContainer.vue";

const { class: className, ...props } = defineProps<
  TableVariants & {
    class?: string;
  }
>();

provide(
  "tableVariant",
  computed(() => ({
    variant: props.variant,
    raised: props.raised,
  }))
);
</script>

<template>
  <TableContainer>
    <table
      :class="cn(tableVariants({ variant, raised }), className)"
      v-bind="{ ...props }"
    >
      <slot />
    </table>
  </TableContainer>
</template>
