// packages/vue/src/components/ui/textarea/Textarea.vue
<script lang="ts" setup>
import { cn } from "@/utils/cn";
import { textarea } from "@midoneui/core/styles/textarea.styles";

const { class: className, ...props } = defineProps<{
  class?: string;
}>();
</script>

<template>
  <textarea :class="cn(textarea, className)" v-bind="{ ...props }" />
</template>

// packages/react/src/components/ui/textarea/index.tsx
import { cn } from "@midoneui/core/utils/cn";
import { textarea } from "@midoneui/core/styles/textarea.styles";

function Textarea({
  className,
  children,
  ...props
}: React.ComponentProps<"textarea">) {
  return <textarea className={cn(textarea, className)} {...props} />;
}

export { Textarea };
