// packages/react/src/components/ui/native-select/index.tsx
import { cn } from "@/utils/cn";
import { input } from "@midoneui/core/styles/input.styles";
import {
  nativeSelect,
  nativeSelectOption,
  NativeSelectOptGroup,
} from "@midoneui/core/styles/native-select.styles";

function NativeSelect({
  children,
  className,
  ...props
}: React.ComponentProps<"select">) {
  return (
    <select className={cn(input, nativeSelect, className)} {...props}>
      {children}
    </select>
  );
}

function NativeSelectOption({
  children,
  className,
  ...props
}: React.ComponentProps<"option">) {
  return (
    <option className={cn(nativeSelectOption, className)} {...props}>
      {children}
    </option>
  );
}

function NativeSelectOptionGroup({
  children,
  className,
  ...props
}: React.ComponentProps<"optgroup">) {
  return (
    <optgroup className={cn(NativeSelectOptGroup, className)} {...props}>
      {children}
    </optgroup>
  );
}

export { NativeSelect, NativeSelectOption, NativeSelectOptionGroup };

// packages/svelte/src/components/ui/native-select/NativeSelect.svelte
<script lang="ts">
  import { cn } from "@midoneui/core/utils/cn";
  import { nativeSelect } from "@midoneui/core/styles/native-select.styles";
  import { Label } from "@/components/ui/label";
  import type { Snippet } from "svelte";

  let {
    class: className,
    label: labelText,
    children,
    ...props
  }: { class?: string; label?: string; children?: Snippet } & Record<string, any> = $props();
</script>

<div class="flex flex-col gap-2.5 {className ?? ''}" {...props}>
  {#if labelText}
    <Label>{labelText}</Label>
  {/if}
  <select class={cn(nativeSelect)}>
    {@render children?.()}
  </select>
</div>
