// packages/react/src/components/ui/carousel/index.tsx
import { createContext, useContext, useId } from "react";
import { cn } from "@midoneui/core/utils/cn";
import { Button } from "@/components/ui/button";
import {
  carouselRoot,
  carouselControl,
  carouselPrevTrigger,
  carouselNextTrigger,
  carouselIndicatorGroup,
  carouselIndicator,
  carouselItemGroup,
  carouselItem,
} from "@midoneui/core/styles/carousel.styles";
import { ArrowLeft, ArrowRight } from "lucide-react";
import { Box } from "../box";
import * as carousel from "@zag-js/carousel";
import { useMachine, normalizeProps } from "@zag-js/react";
import type { Api, IndicatorProps, ItemProps, Props } from "@zag-js/carousel";
import { Slot } from "@/components/ui/slot";

const ApiContext = createContext<Api | null>(null);

export function CarouselRoot({
  children,
  className,
  defaultPage,
  slideCount,
  asChild = false,
  ...props
}: React.ComponentProps<"div"> & Partial<Props> & { asChild?: boolean }) {
  const service = useMachine(carousel.machine, {
    defaultPage,
    slideCount,
    ...props,
    id: useId(),
  });
  const api = carousel.connect(service, normalizeProps);

  return (
    <ApiContext.Provider value={api}>
      <Slot
        className={cn(carouselRoot, className)}
        {...api.getRootProps()}
        {...props}
      >
        {asChild ? children : <div>{children}</div>}
      </Slot>
    </ApiContext.Provider>
  );
}

export function CarouselControl({
  children,
  className,
  asChild = false,
  ...props
}: React.ComponentProps<"div"> & { asChild?: boolean }) {
  const api = useContext(ApiContext);

  return (
    <Slot
      className={cn(carouselControl, className)}
      {...api?.getControlProps()}
      {...props}
    >
      {asChild ? children : <div>{children}</div>}
    </Slot>
  );
}

export function CarouselPrevTrigger({
  children,
  className,
  asChild = false,
  ...props
}: React.ComponentProps<"div"> & { asChild?: boolean }) {
  const api = useContext(ApiContext);

  return (
    <Slot {...api?.getPrevTriggerProps()} {...props}>
      {asChild ? (
        children
      ) : (
        <Button className={cn(carouselPrevTrigger, className)}>
          {children ?? <ArrowLeft />}
        </Button>
      )}
    </Slot>
  );
}

export function CarouselNextTrigger({
  children,
  className,
  asChild = false,
  ...props
}: React.ComponentProps<"div"> & { asChild?: boolean }) {
  const api = useContext(ApiContext);

  return (
    <Slot {...api?.getNextTriggerProps()} {...props}>
      {asChild ? (
        children
      ) : (
        <Button className={cn(carouselNextTrigger, className)}>
          {children ?? <ArrowRight />}
        </Button>
      )}
    </Slot>
  );
}

export function CarouselIndicatorGroup({
  children,
  className,
  asChild = false,
  ...props
}: React.ComponentProps<"div"> & { asChild?: boolean }) {
  const api = useContext(ApiContext);

  return (
    <Slot
      className={cn(carouselIndicatorGroup, className)}
      {...api?.getIndicatorGroupProps()}
      {...props}
    >
      {asChild ? children : <div>{children}</div>}
    </Slot>
  );
}

export function CarouselIndicator({
  className,
  asChild = false,
  index,
  ...props
}: React.ComponentProps<"button"> & { asChild?: boolean } & IndicatorProps) {
  const api = useContext(ApiContext);

  return (
    <button
      className={cn(carouselIndicator, className)}
      {...api?.getIndicatorProps({ index })}
      {...props}
    />
  );
}

export function CarouselItemGroup({
  children,
  className,
  asChild = false,
  ...props
}: React.ComponentProps<"div"> & { asChild?: boolean }) {
  const api = useContext(ApiContext);

  return (
    <Slot
      className={cn(carouselItemGroup, className)}
      {...api?.getItemGroupProps()}
      {...props}
    >
      {asChild ? children : <div>{children}</div>}
    </Slot>
  );
}

export function CarouselItem({
  children,
  className,
  asChild = false,
  index,
  ...props
}: React.ComponentProps<"div"> & { asChild?: boolean } & ItemProps) {
  const api = useContext(ApiContext);

  return (
    <Slot {...api?.getItemProps({ index })} {...props}>
      {asChild ? (
        children
      ) : (
        <Box className={cn(carouselItem, className)}>{children}</Box>
      )}
    </Slot>
  );
}

// packages/svelte/src/components/ui/carousel/Carousel.svelte
<script lang="ts">
  import * as carousel from "@zag-js/carousel";
  import { useMachine, normalizeProps } from "@zag-js/svelte";
  import { cn } from "@midoneui/core/utils/cn";
  import { carouselRoot, carouselControl, carouselPrevTrigger, carouselNextTrigger, carouselIndicatorGroup, carouselIndicator, carouselItemGroup, carouselItem } from "@midoneui/core/styles/carousel.styles";
  import { ChevronLeft, ChevronRight } from "lucide-svelte";
  import type { Snippet } from "svelte";

  let {
    class: className,
    slides = [],
    children,
    ...props
  }: { class?: string; slides?: any[]; children?: Snippet } & Record<string, any> = $props();

  const service = useMachine(carousel.machine, () => ({
    ...props,
    id: crypto.randomUUID(),
    slideCount: slides.length,
  }));
  const api = $derived(carousel.connect(service, normalizeProps));
</script>

<div class={cn(carouselRoot, className)} {...api.getRootProps()}>
  <div class="overflow-hidden" {...api.getViewportProps()}>
    <div class={cn(carouselItemGroup)} {...api.getItemGroupProps()}>
      {#each slides as slide, index}
        <div class={cn(carouselItem)} {...api.getItemProps({ index })}>
          {#if typeof slide === "string"}
            <img src={slide} alt="Slide {index + 1}" class="w-full h-full object-cover" />
          {:else}
            <div class="w-full h-48 bg-foreground/5 rounded flex items-center justify-center">
              Slide {index + 1}
            </div>
          {/if}
        </div>
      {/each}
    </div>
  </div>
  <div class={cn(carouselControl)}>
    <button class={cn(carouselPrevTrigger)} {...api.getPrevTriggerProps()}>
      <ChevronLeft class="size-4" />
    </button>
    <div class={cn(carouselIndicatorGroup)} {...api.getIndicatorGroupProps()}>
      {#each slides as _, index}
        <button class={cn(carouselIndicator)} {...api.getIndicatorProps({ index })}></button>
      {/each}
    </div>
    <button class={cn(carouselNextTrigger)} {...api.getNextTriggerProps()}>
      <ChevronRight class="size-4" />
    </button>
  </div>
</div>
