// packages/vue/src/components/ui/tabs/TabsTrigger.vue
<script lang="ts" setup>
import { cn } from "@/utils/cn";
import { tabsTrigger } from "@midoneui/core/styles/tabs.styles";
import type { Api, TriggerProps } from "@zag-js/tabs";
import { inject } from "vue";
import { Slot } from "@/components/ui/slot";

const {
  class: className,
  asChild = false,
  ...props
} = defineProps<
  TriggerProps & {
    class?: string;
    asChild?: boolean;
  }
>();

const api = inject<Api>("tabsApi");
</script>

<template>
  <Slot
    :class="cn(tabsTrigger, className)"
    v-bind="{ ...props, ...$attrs, ...api?.getTriggerProps(props) }"
  >
    <slot v-if="asChild" />
    <button v-else>
      <slot />
    </button>
  </Slot>
</template>

// packages/svelte/src/components/ui/tabs/TabsTrigger.svelte
<script lang="ts">
  import { cn } from "@midoneui/core/utils/cn";
  import { tabsTrigger } from "@midoneui/core/styles/tabs.styles";
  import { getContext } from "svelte";
  import type { Snippet } from "svelte";

  let {
    class: className,
    value,
    children,
    ...props
  }: { class?: string; value: string; children?: Snippet } & Record<string, any> = $props();

  const getApi = getContext<() => any>("tabsApi");
  const api = $derived(getApi());
</script>

<button class={cn(tabsTrigger, className)} {...api?.getTriggerProps({ value })} {...props}>
  {@render children?.()}
</button>
