// packages/vue/src/components/ui/accordion/AccordionRoot.vue
<script lang="ts" setup>
import { accordionRootVariants } from "@midoneui/core/styles/accordion.styles";
import { cn } from "@/utils/cn";
import { provide, computed } from "vue";
import * as accordion from "@zag-js/accordion";
import type { Props } from "@zag-js/accordion";
import { useMachine, normalizeProps } from "@zag-js/vue";
import { Slot } from "@/components/ui/slot";

const {
  class: className,
  variant = "default",
  asChild = false,
  collapsible = true,
  ...props
} = defineProps<
  Partial<Props> & {
    class?: string;
    variant?: "default" | "boxed";
    asChild?: boolean;
  }
>();

const service = useMachine(accordion.machine, {
  collapsible,
  ...props,
  id: crypto.randomUUID(),
});

const api = computed(() => accordion.connect(service, normalizeProps));

provide("accordionVariant", variant);
provide("accordionApi", api);
</script>

<template>
  <Slot
    :class="cn([className, accordionRootVariants({ variant })])"
    v-bind="{ ...props, ...$attrs, ...api.getRootProps() }"
  >
    <slot v-if="asChild" />
    <div v-else>
      <slot />
    </div>
  </Slot>
</template>

// packages/svelte/src/components/ui/accordion/AccordionRoot.svelte
<script lang="ts">
  import { accordionRootVariants } from "@midoneui/core/styles/accordion.styles";
  import { cn } from "@midoneui/core/utils/cn";
  import * as accordion from "@zag-js/accordion";
  import { useMachine, normalizeProps } from "@zag-js/svelte";
  import { setContext } from "svelte";
  import type { Snippet } from "svelte";

  let {
    class: className,
    variant = "default",
    collapsible = true,
    asChild = false,
    children,
    ...props
  }: {
    class?: string;
    variant?: "default" | "boxed";
    collapsible?: boolean;
    asChild?: boolean;
    children?: Snippet<[Record<string, any>]>;
  } & Record<string, any> = $props();

  const service = useMachine(accordion.machine, () => ({
    collapsible,
    ...props,
    id: crypto.randomUUID(),
  }));

  const api = $derived(accordion.connect(service, normalizeProps));

  setContext("accordionVariant", () => variant);
  setContext("accordionApi", () => api);
</script>

{#if asChild}
  {@render children?.({
    class: cn(accordionRootVariants({ variant, className }), className),
    ...api.getRootProps(),
  })}
{:else}
  <div class={cn(accordionRootVariants({ variant, className }), className)} {...api.getRootProps()}>
    {@render children?.({})}
  </div>
{/if}
