// packages/vue/src/components/ui/accordion/AccordionContent.vue
<script lang="ts" setup>
import { accordionContent } from "@midoneui/core/styles/accordion.styles";
import { cn } from "@/utils/cn";
import { inject } from "vue";
import { Slot } from "@/components/ui/slot";
import type { Api, ItemProps } from "@zag-js/accordion";

const {
  class: className,
  asChild = false,
  ...props
} = defineProps<{
  class?: string;
  asChild?: boolean;
}>();

const api = inject<Api>("accordionApi");
const item = inject<ItemProps>("accordionItem");
</script>

<template>
  <Slot
    :class="cn([className, accordionContent])"
    v-bind="{ ...props, ...$attrs, ...api?.getItemContentProps(item!) }"
  >
    <slot v-if="asChild" />
    <div v-else>
      <slot />
    </div>
  </Slot>
</template>

// packages/svelte/src/components/ui/accordion/AccordionContent.svelte
<script lang="ts">
  import { accordionContent } from "@midoneui/core/styles/accordion.styles";
  import { cn } from "@midoneui/core/utils/cn";
  import { getContext } from "svelte";
  import type { Snippet } from "svelte";

  let {
    class: className,
    asChild = false,
    children,
    ...props
  }: { class?: string; children?: Snippet<[Record<string, any>]>; asChild?: boolean } & Record<string, any> = $props();

  const getApi = getContext<() => any>("accordionApi");
  const getItem = getContext<() => any>("accordionItem");
  const api = $derived(getApi());
  const item = $derived(getItem());
</script>

{#if asChild}
  {@render children?.({
    class: cn(accordionContent, className),
    ...api?.getItemContentProps(item),
    ...props
  })}
{:else}
  <div class={cn(accordionContent, className)} {...api?.getItemContentProps(item)} {...props}>
    {@render children?.({})}
  </div>
{/if}
