// packages/react/src/components/ui/button/index.tsx
import { cn } from "@midoneui/core/utils/cn";
import {
  buttonVariants,
  type ButtonVariants,
} from "@midoneui/core/styles/button.styles";
import { Slot } from "@/components/ui/slot";

function Button({
  className,
  children,
  look,
  variant,
  size,
  asChild = false,
  ...props
}: React.ComponentProps<"button"> & ButtonVariants & { asChild?: boolean }) {
  return (
    <Slot
      {...props}
      className={cn(buttonVariants({ look, variant, size }), className)}
    >
      {asChild ? children : <button>{children}</button>}
    </Slot>
  );
}

export { Button };

// packages/vue/src/components/ui/button/Button.vue
<script lang="ts" setup>
import { cn } from "@/utils/cn";
import {
  buttonVariants,
  type ButtonVariants,
} from "@midoneui/core/styles/button.styles";
import { Slot } from "@/components/ui/slot";

const {
  class: className,
  look,
  variant,
  size,
  asChild = false,
  ...props
} = defineProps<
  ButtonVariants & {
    class?: string;
    asChild?: boolean;
  }
>();
</script>

<template>
  <Slot
    v-bind="{ ...props, ...$attrs }"
    :class="cn(buttonVariants({ look, variant, size }), className)"
  >
    <slot v-if="asChild" />
    <button v-else>
      <slot />
    </button>
  </Slot>
</template>
