// packages/vue/src/pages/Switch.vue
<script lang="ts" setup>
import { SwitchRoot, SwitchControl, SwitchLabel } from "@/components/ui/switch";
</script>

<template>
  <div class="flex flex-col gap-20">
    <div class="grid grid-cols-2">
      <div class="justify-center items-center flex gap-2 border-b border-e border-foreground/10 p-5 flex-wrap">
        <SwitchRoot label="Airplane Mode" />
      </div>
      <div class="justify-center items-center flex gap-2 border-b border-e border-foreground/10 p-5 flex-wrap">
        <SwitchRoot>
          <SwitchControl />
          <SwitchLabel class="font-normal">
              Activate PreOrder if you need a longer shipping process.
              <a class="text-primary" href="">
                  Learn more
              </a>
              .
          </SwitchLabel>
        </SwitchRoot>
      </div>
    </div>
  </div>
</template>

// packages/react/src/pages/react/switch.tsx
import { SwitchRoot, SwitchControl, SwitchLabel } from "@/components/ui/switch";
import {
  Preview,
  SectionTitle,
  SectionContent,
  InstallPackage,
  PreviewCode,
} from "@/components/docs";

function Main() {
  return (
    <>
      <div id="preview" className="-mt-20">
        <Preview>
          {() => ({
            preview: (
              <>
                <div className="flex flex-col gap-20">
                  <div className="grid grid-cols-2">
                    <div className="justify-center items-center flex gap-2 border-b border-e border-foreground/10 p-5 flex-wrap">
                      <SwitchRoot label="Airplane Mode" />
                    </div>
                    <div className="justify-center items-center flex gap-2 border-b border-e border-foreground/10 p-5 flex-wrap">
                      <SwitchRoot>
                        <SwitchControl />
                        <SwitchLabel className="font-normal">
                          Activate PreOrder if you need a longer shipping process.{" "}
                          <a className="text-primary" href="">
                            Learn more
                          </a>
                          .
                        </SwitchLabel>
                      </SwitchRoot>
                    </div>
                  </div>
                </div>
              </>
            ),
            code: (
              <PreviewCode>
                {`
<div className="flex flex-col gap-20">
  <div className="grid grid-cols-2">
    <div className="justify-center items-center flex gap-2 border-b border-e border-foreground/10 p-5 flex-wrap">
      <SwitchRoot label="Airplane Mode" />
    </div>
    <div className="justify-center items-center flex gap-2 border-b border-e border-foreground/10 p-5 flex-wrap">
      <SwitchRoot>
        <SwitchControl />
        <SwitchLabel className="font-normal">
          Activate PreOrder if you need a longer shipping process. 
          <a className="text-primary" href="">
              Learn more
          </a>
          .
        </SwitchLabel>
      </SwitchRoot>
    </div>
  </div>
</div>
                        `}
              </PreviewCode>
            ),
          })}
        </Preview>
      </div>
      <div id="installation">
        <SectionTitle>Installation</SectionTitle>
        <SectionContent>Install the following dependencies:</SectionContent>
        <InstallPackage>add @zag-js/react @zag-js/switch</InstallPackage>
        <SectionContent>
          Copy and paste the following code into your project.
        </SectionContent>
        <PreviewCode title="components/ui/switch/index.tsx">
          {`
import { cn } from "@midoneui/core/utils/cn";
import {
  switchRoot,
  switchControl,
  switchThumb,
  switchLabel,
  switchHiddenInput,
} from "@midoneui/core/styles/switch.styles";
import { label } from "@midoneui/core/styles/label.styles";
import * as zagSwitch from "@zag-js/switch";
import { useMachine, normalizeProps } from "@zag-js/react";
import type { Api, Props } from "@zag-js/switch";
import { Slot } from "@/components/ui/slot";
import { createContext, useContext, useId } from "react";

const ApiContext = createContext<Api | null>(null);

export function SwitchRoot({
  children,
  className,
  asChild = false,
  label,
  ...props
}: React.ComponentProps<"label"> & Partial<Props> & { asChild?: boolean; label?: string }) {
  const service = useMachine(zagSwitch.machine, { ...props, id: useId() });
  const api = zagSwitch.connect(service, normalizeProps);

  return (
    <ApiContext.Provider value={api}>
      <Slot
        className={cn(switchRoot, className)}
        {...api?.getRootProps()}
        {...props}
      >
        {asChild ? (
          children
        ) : (
          <label>
            {label ? (
              <>
                <SwitchControl />
                <SwitchLabel>{label}</SwitchLabel>
              </>
            ) : (
              children
            )}
            <SwitchHiddenInput />
          </label>
        )}
      </Slot>
    </ApiContext.Provider>
  );
}

export function SwitchControl({
  children,
  className,
  asChild = false,
  ...props
}: React.ComponentProps<"span"> & { asChild?: boolean }) {
  const api = useContext(ApiContext);

  return (
    <Slot
      className={cn(switchControl, className)}
      {...api?.getControlProps()}
      {...props}
    >
      {asChild ? (
        children
      ) : (
        <span>
          <SwitchThumb />
        </span>
      )}
    </Slot>
  );
}

export function SwitchThumb({
  children,
  className,
  asChild = false,
  ...props
}: React.ComponentProps<"span"> & { asChild?: boolean }) {
  const api = useContext(ApiContext);

  return (
    <Slot
      className={cn(switchThumb, className)}
      {...api?.getThumbProps()}
      {...props}
    >
      {asChild ? children : <span>{children}</span>}
    </Slot>
  );
}

export function SwitchLabel({
  children,
  className,
  asChild = false,
  ...props
}: React.ComponentProps<"span"> & { asChild?: boolean }) {
  const api = useContext(ApiContext);

  return (
    <Slot
      className={cn([label, switchLabel, className])}
      {...api?.getLabelProps()}
      {...props}
    >
      {asChild ? children : <span>{children}</span>}
    </Slot>
  );
}

export function SwitchHiddenInput({
  className,
  ...props
}: React.ComponentProps<"input">) {
  const api = useContext(ApiContext);

  return (
    <input
      className={cn(switchHiddenInput, className)}
      {...api?.getHiddenInputProps()}
      {...props}
    />
  );
}
              `}
        </PreviewCode>
        <SectionContent>
          Update the import paths to match your project setup.
        </SectionContent>
      </div>
      <div id="usage">
        <SectionTitle>Usage</SectionTitle>
        <PreviewCode>
          {`
import { SwitchRoot } from "@/components/ui/switch";
              `}
        </PreviewCode>
        <PreviewCode>
          {`
<SwitchRoot label="Airplane Mode" />
              `}
        </PreviewCode>
      </div>
    </>
  );
}

export default Main;
