// packages/react/src/components/ui/separator/index.tsx
import { cn } from "@/utils/cn"
import { separator } from "@midoneui/core/styles/separator.styles";

export function Separator({
    className,
    orientation = "horizontal",
    decorative = true,
    ...props
}: React.ComponentProps<"div"> & {
    orientation?: "vertical" | "horizontal" | "responsive";
    decorative?: boolean;
}) {
    return (
        <div
            data-part="separator"
            data-decorative={decorative}
            data-orientation={orientation}
            className={cn(separator, className)}
            {...props}
        />
    );
}

// packages/vue/src/components/ui/separator/Separator.vue
<script lang="ts" setup>
import { cn } from "@/utils/cn";
import { separator } from "@midoneui/core/styles/separator.styles";

const {
  class: className,
  orientation = "horizontal",
  decorative = true,
  ...props
} = defineProps<{
  class?: string;
  asChild?: boolean;
  orientation?: "vertical" | "horizontal" | "responsive";
  decorative?: boolean;
}>();
</script>

<template>
  <div
    data-part="separator"
    :data-decorative="decorative"
    :data-orientation="orientation"
    :class="cn(separator, className)"
    v-bind="{ ...props }"
  />
</template>
