// packages/svelte/src/components/ui/menu/MenuTrigger.svelte
<script lang="ts">
  import { cn } from "@midoneui/core/utils/cn";
  import { menuTrigger } from "@midoneui/core/styles/menu.styles";
  import { Button } from "@/components/ui/button";
  import { getContext } from "svelte";
  import type { Snippet } from "svelte";

  let { class: className, children, ...props }: { class?: string; children?: Snippet } & Record<string, any> = $props();
  const getApi = getContext<() => any>("menuApi");
  const api = $derived(getApi());
</script>

<Button variant="secondary" look="outline" class={cn(menuTrigger, className)} {...api?.getTriggerProps()} {...props}>
  {@render children?.()}
</Button>

// packages/vue/src/components/ui/menu/MenuTrigger.vue
<script lang="ts" setup>
import { type Api } from "@zag-js/menu";
import { cn } from "@/utils/cn";
import { inject } from "vue";
import { Button } from "@/components/ui/button";
import { Slot } from "@/components/ui/slot";
import { menuTrigger } from "@midoneui/core/styles/menu.styles";
import { MenuIndicator } from ".";

const {
  class: className,
  asChild = false,
  ...props
} = defineProps<{
  class?: string;
  asChild?: boolean;
}>();

const api = inject<Api>("menuApi");
</script>

<template>
  <Slot v-bind="{ ...api?.getTriggerProps(), ...props, ...$attrs }">
    <Button variant="ghost" v-if="!asChild" :class="cn(menuTrigger, className)">
      <slot />
      <MenuIndicator />
    </Button>
    <slot v-else />
  </Slot>
</template>
