// packages/svelte/src/components/ui/menu/MenuRoot.svelte
<script lang="ts">
  import * as menu from "@zag-js/menu";
  import { useMachine, normalizeProps } from "@zag-js/svelte";
  
  import { setContext } from "svelte";
  import type { Snippet } from "svelte";

  let {
    class: className,
    children,
    ...props
  }: { class?: string; children?: Snippet } & Record<string, any> = $props();

  const service = useMachine(menu.machine, () => ({ ...props, id: crypto.randomUUID() }));
  const api = $derived(menu.connect(service, normalizeProps));

  setContext("menuApi", () => api);
</script>

{@render children?.()}

// packages/vue/src/components/ui/menu/MenuRoot.vue
<script lang="ts" setup>
import * as menu from "@zag-js/menu";
import { type Api } from "@zag-js/menu";
import { Slot } from "@/components/ui/slot";
import { cn } from "@midoneui/core/utils/cn";
import { normalizeProps, useMachine } from "@zag-js/vue";
import { computed, provide, type ComputedRef } from "vue";
import { menuRoot } from "@midoneui/core/styles/menu.styles";

const service = useMachine(menu.machine, { id: crypto.randomUUID() });
const api = computed(() => menu.connect(service, normalizeProps));

interface Props {
  class?: string;
  asChild?: boolean;
}

const { class: className, ...props } = defineProps<Props>();
provide<ComputedRef<Api>>("menuApi", api);
</script>

<template>
  <Slot v-bind="{ ...props, ...$attrs }">
    <div v-if="!props.asChild" :class="cn(menuRoot, className)">
      <slot />
    </div>
    <slot v-else />
  </Slot>
</template>
