// packages/svelte/src/components/ui/box/Box.svelte
<script lang="ts">
  import { cn } from "@midoneui/core/utils/cn";
  import {
    boxVariants,
    type BoxVariants,
  } from "@midoneui/core/styles/box.styles";
  import type { Snippet } from "svelte";

  let {
    class: className,
    raised,
    children,
    ...props
  }: BoxVariants & {
    class?: string;
    children?: Snippet;
  } & Record<string, any> = $props();
</script>

<div class={cn(boxVariants({ raised, className }), className)} {...props}>
  {@render children?.()}
</div>

// packages/react/src/components/ui/box/index.tsx
import { cn } from "@midoneui/core/utils/cn";
import {
  boxVariants,
  type BoxVariants,
} from "@midoneui/core/styles/box.styles";

function Box({
  children,
  className,
  raised,
  ...props
}: React.ComponentProps<"div"> & BoxVariants) {
  return (
    <div
      className={cn(boxVariants({ raised, className }), className)}
      {...props}
    >
      {children}
    </div>
  );
}

export { Box };
