// packages/svelte/src/components/ui/popover/PopoverContent.svelte
<script lang="ts">
  import { cn } from "@midoneui/core/utils/cn";
  import { popoverContent, popoverPositioner } from "@midoneui/core/styles/popover.styles";
  import { Box } from "@/components/ui/box";
  import { getContext } from "svelte";
  import type { Snippet } from "svelte";

  let { class: className, children, ...props }: { class?: string; children?: Snippet } & Record<string, any> = $props();
  const getApi = getContext<() => any>("popoverApi");
  const api = $derived(getApi());
</script>

<div class={cn(popoverPositioner)} {...api?.getPositionerProps()}>
  <div {...api?.getContentProps()} {...props}>
    <Box raised="double" class={cn(popoverContent, className)}>
      {@render children?.()}
    </Box>
  </div>
</div>

// packages/vue/src/components/ui/popover/PopoverContent.vue
<script lang="ts" setup>
import { type Api } from "@zag-js/popover";
import { cn } from "@/utils/cn";
import { inject } from "vue";
import { Slot } from "@/components/ui/slot";
import { popoverContent } from "@midoneui/core/styles/popover.styles";
import { PopoverArrow, PopoverArrowTip, PopoverPositioner } from ".";
import { Box } from "@/components/ui/box";

const {
  class: className,
  asChild = false,
  ...props
} = defineProps<{
  class?: string;
  asChild?: boolean;
}>();

const api = inject<Api>("popoverApi");
</script>

<template>
  <PopoverPositioner>
    <Slot
      :class="cn(popoverContent, className)"
      v-bind="{ ...api?.getContentProps(), ...props, ...$attrs }"
    >
      <slot v-if="asChild" />
      <Box v-else raised="single" :class="cn(popoverContent, className)">
        <div><slot /></div>
        <PopoverArrow>
          <PopoverArrowTip />
        </PopoverArrow>
      </Box>
    </Slot>
  </PopoverPositioner>
</template>
