// packages/svelte/src/components/ui/chart/ChartComponent.svelte
<script lang="ts">
  import { cn } from "@midoneui/core/utils/cn";
  import Chart from "chart.js/auto";
  import { onMount, onDestroy } from "svelte";

  let {
    class: className,
    type = "bar",
    data,
    options = {},
    ...props
  }: { class?: string; type?: string; data: any; options?: any } & Record<string, any> = $props();

  let canvasEl: HTMLCanvasElement;
  let chart: Chart | null = null;

  onMount(() => {
    chart = new Chart(canvasEl, {
      type: type as any,
      data,
      options: {
        responsive: true,
        maintainAspectRatio: false,
        ...options,
      },
    });
  });

  onDestroy(() => {
    chart?.destroy();
  });
</script>

<div class={cn("relative", className)} {...props}>
  <canvas bind:this={canvasEl}></canvas>
</div>

// packages/vue/src/components/ui/chart/Chart.vue
<script lang="ts" setup>
import ChartJs from "chart.js/auto";
import { ref, onMounted } from "vue";
import { cn } from "@midoneui/core/utils/cn";
import { chart } from "@midoneui/core/styles/chart.styles";

const {
  class: className,
  config,
  ...props
} = defineProps<{
  class?: string;
  config: ConstructorParameters<typeof ChartJs>[1];
}>();

const chartRef = ref<
  | (HTMLCanvasElement & {
      instance?: {};
    })
  | null
>(null);

onMounted(() => {
  if (chartRef.value && !chartRef.value.instance) {
    chartRef.value.instance = new ChartJs(chartRef.value, config);
  }
});
</script>

<template>
  <canvas :class="cn(chart, className)" ref="chartRef" v-bind="props" />
</template>
