// packages/svelte/src/components/ui/accordion/AccordionTrigger.svelte
<script lang="ts">
  import { ChevronDown } from "lucide-svelte";
  import { accordionTrigger, accordionItemIndicator } from "@midoneui/core/styles/accordion.styles";
  import { cn } from "@midoneui/core/utils/cn";
  import { getContext } from "svelte";
  import type { Snippet } from "svelte";

  let {
    class: className,
    asChild = false,
    children,
    ...props
  }: { class?: string; children?: Snippet<[Record<string, any>]>; asChild?: boolean } & Record<string, any> = $props();

  const getApi = getContext<() => any>("accordionApi");
  const getItem = getContext<() => any>("accordionItem");
  const api = $derived(getApi());
  const item = $derived(getItem());
</script>

{#if asChild}
  {@render children?.({
    class: cn(accordionTrigger, className),
    ...api?.getItemTriggerProps(item),
    ...props
  })}
{:else}
  <button class={cn(accordionTrigger, className)} {...api?.getItemTriggerProps(item)} {...props}>
    {@render children?.({})}
    <div {...api?.getItemIndicatorProps(item)} class={cn(accordionItemIndicator)}>
      <ChevronDown />
    </div>
  </button>
{/if}

// packages/vue/src/components/ui/accordion/AccordionTrigger.vue
<script lang="ts" setup>
import { ChevronDownIcon } from "lucide-vue-next";
import {
  accordionTrigger,
  accordionItemIndicator,
} from "@midoneui/core/styles/accordion.styles";
import { cn } from "@/utils/cn";
import { inject } from "vue";
import { Slot } from "@/components/ui/slot";
import type { Api, ItemProps } from "@zag-js/accordion";

const {
  class: className,
  asChild = false,
  ...props
} = defineProps<{
  class?: string;
  asChild?: boolean;
}>();

const api = inject<Api>("accordionApi");
const item = inject<ItemProps>("accordionItem");
</script>

<template>
  <Slot
    :class="cn([className, accordionTrigger])"
    v-bind="{ ...props, ...$attrs, ...api?.getItemTriggerProps(item!) }"
  >
    <slot v-if="asChild" />
    <button v-else>
      <slot />
      <div
        v-bind="api?.getItemIndicatorProps(item!)"
        :class="cn(accordionItemIndicator)"
      >
        <ChevronDownIcon />
      </div>
    </button>
  </Slot>
</template>
