// packages/svelte/src/components/ui/accordion/AccordionItem.svelte
<script lang="ts">
  import { accordionItemVariants } from "@midoneui/core/styles/accordion.styles";
  import { boxVariants, type BoxVariants } from "@midoneui/core/styles/box.styles";
  import { cn } from "@midoneui/core/utils/cn";
  import { getContext, setContext } from "svelte";
  import type { Snippet } from "svelte";
  import type { ItemProps } from "@zag-js/accordion";

  let {
    raised,
    class: className,
    value,
    asChild = false,
    children,
    ...props
  }: BoxVariants & ItemProps & { class?: string; children?: Snippet<[Record<string, any>]>; asChild?: boolean } & Record<string, any> = $props();

  const getVariant = getContext<() => string>("accordionVariant");
  const getApi = getContext<() => any>("accordionApi");
  const variant = $derived(getVariant());
  const api = $derived(getApi());

  setContext("accordionItem", () => ({ value }));
</script>

{#if asChild}
  {@render children?.({
    class: cn(
    variant === "boxed" ? boxVariants({ raised, className }) : "",
    accordionItemVariants({ variant: variant as any, className }),
    className
  ),
  ...api?.getItemProps({ value })
})}
{:else}
  <div
    class={cn(
      variant === "boxed" ? boxVariants({ raised, className }) : "",
      accordionItemVariants({ variant: variant as any, className }),
      className
    )}
    {...api?.getItemProps({ value })}
  >
    {@render children?.({})}
  </div>
{/if}

// packages/vue/src/components/ui/accordion/AccordionItem.vue
<script lang="ts" setup>
import { accordionItemVariants } from "@midoneui/core/styles/accordion.styles";
import {
  boxVariants,
  type BoxVariants,
} from "@midoneui/core/styles/box.styles";
import { cn } from "@/utils/cn";
import { inject, provide } from "vue";
import { Slot } from "@/components/ui/slot";
import type { Api, ItemProps } from "@zag-js/accordion";

const {
  raised,
  class: className,
  asChild = false,
  ...props
} = defineProps<
  BoxVariants & ItemProps & { class?: string; asChild?: boolean }
>();

const variant = inject<"default" | "boxed">("accordionVariant", "default");
const api = inject<Api>("accordionApi");

provide("accordionItem", props);
</script>

<template>
  <Slot
    :class="
      cn([
        className,
        variant == 'boxed' ? boxVariants({ raised }) : '',
        accordionItemVariants({ variant }),
      ])
    "
    v-bind="{ ...props, ...$attrs, ...api?.getItemProps(props) }"
  >
    <slot v-if="asChild" />
    <div v-else>
      <slot />
    </div>
  </Slot>
</template>
