// packages/docs/src/components/ui/lucide/index.tsx
import * as lucideIcons from "lucide-react";
import { cn } from "@midoneui/core/utils/cn";

export type Icon = keyof typeof lucideIcons;

export interface LucideProps extends React.ComponentPropsWithoutRef<"svg"> {
  icon: Icon;
}

export function Lucide({ icon, className, ...props }: LucideProps) {
  const IconComponent = lucideIcons[icon] as React.ElementType;

  if (!IconComponent) {
    return null;
  }

  return (
    <IconComponent
      className={cn(
        "size-4 stroke-[1.5] [--color:currentColor] stroke-(--color) fill-(--color)/25",
        className
      )}
      {...props}
    />
  );
}

// packages/vue/src/components/ui/lucide/Lucide.vue
<script setup lang="ts">
import * as lucideIcons from 'lucide-vue-next'
import { cn } from '@/utils/cn'
import { computed, type HTMLAttributes } from 'vue'

export type Icon = keyof typeof lucideIcons

const props = defineProps<{
  icon: Icon
  class?: HTMLAttributes['class']
}>()

const iconComponent = computed(() => lucideIcons[props.icon] as any)
</script>

<template>
  <component
    :is="iconComponent"
    :class="
      cn(
        'size-4 stroke-[1.5] [--color:currentColor] stroke-(--color) fill-(--color)/25',
        props.class,
      )
    "
  />
</template>
