// packages/vue/src/components/ui/alert/AlertDescription.vue
<script lang="ts" setup>
import { cn } from "@midoneui/core/utils/cn";
import { alertDescription } from "@midoneui/core/styles/alert.styles";

const props = defineProps<{
  class?: string;
}>();
</script>

<template>
  <div :class="cn([props.class, alertDescription])" v-bind="props">
    <slot />
  </div>
</template>

// packages/svelte/src/components/ui/alert/AlertDescription.svelte
<script lang="ts">
  import { cn } from "@midoneui/core/utils/cn";
  import { alertDescription } from "@midoneui/core/styles/alert.styles";
  import type { Snippet } from "svelte";

  let {
    class: className,
    children,
    ...props
  }: { class?: string; children?: Snippet } & Record<string, any> = $props();
</script>

<div class={cn(alertDescription, className)} {...props}>
  {@render children?.()}
</div>
