// packages/vue/src/components/ui/alert/AlertRoot.vue
<script lang="ts" setup>
import { cn } from "@/utils/cn";
import {
  alertRootVariants,
  type AlertRootVariants,
} from "@midoneui/core/styles/alert.styles";
import { Presence } from "@/components/ui/presence";
import { ref, provide } from "vue";

const {
  class: className,
  look,
  variant,
  ...rest
} = defineProps<AlertRootVariants & { class?: string }>();

const present = ref(true);
const setPresent = (value: boolean) => {
  present.value = value;
};

provide("alertPresent", { present, setPresent });
</script>

<template>
  <Presence
    :class="
      cn(
        alertRootVariants({
          look,
          variant,
        }),
        className
      )
    "
    v-bind="rest"
    :present="present"
  >
    <slot />
  </Presence>
</template>

// packages/svelte/src/components/ui/alert/AlertRoot.svelte
<script lang="ts">
  import { cn } from "@midoneui/core/utils/cn";
  import { alertRootVariants, type AlertRootVariants } from "@midoneui/core/styles/alert.styles";
  import { Presence } from "@/components/ui/presence";
  import { setContext } from "svelte";
  import type { Snippet } from "svelte";

  let {
    class: className,
    look,
    variant,
    children,
    ...rest
  }: AlertRootVariants & { class?: string; children?: Snippet } & Record<string, any> = $props();

  let present = $state(true);
  const setPresent = (value: boolean) => { present = value; };

  setContext("alertPresent", { getPresent: () => present, setPresent });
</script>

<Presence
  class={cn(alertRootVariants({ look, variant }), className)}
  {present}
  {...rest}
>
  {@render children?.()}
</Presence>
