// packages/vue/src/components/ui/table/TableHeader.vue
<script lang="ts" setup>
import { cn } from "@/utils/cn";
import { tableHeader } from "@midoneui/core/styles/table.styles";

const { class: className, ...props } = defineProps<{
  class?: string;
}>();
</script>

<template>
  <thead :class="cn(tableHeader, className)" v-bind="{ ...props }">
    <slot />
  </thead>
</template>

// packages/svelte/src/components/ui/table/TableHeader.svelte
<script lang="ts">
  import { cn } from "@midoneui/core/utils/cn";
  import { tableHeader } from "@midoneui/core/styles/table.styles";
  import type { Snippet } from "svelte";

  let { class: className, children, ...props }: { class?: string; children?: Snippet } & Record<string, any> = $props();
</script>

<thead class={cn(tableHeader, className)} {...props}>
  {@render children?.()}
</thead>
