// packages/vue/src/components/ui/table/TableHead.vue
<script lang="ts" setup>
import { cn } from "@/utils/cn";
import { tableHead } from "@midoneui/core/styles/table.styles";

const { class: className, ...props } = defineProps<{
  class?: string;
}>();
</script>

<template>
  <th :class="cn(tableHead, className)" v-bind="{ ...props }">
    <slot />
  </th>
</template>

// packages/svelte/src/components/ui/table/TableHead.svelte
<script lang="ts">
  import { cn } from "@midoneui/core/utils/cn";
  import { tableHead } from "@midoneui/core/styles/table.styles";
  import type { Snippet } from "svelte";

  let { class: className, children, ...props }: { class?: string; children?: Snippet } & Record<string, any> = $props();
</script>

<th class={cn(tableHead, className)} {...props}>
  {@render children?.()}
</th>
