// packages/vue/src/components/ui/checkbox/CheckboxControl.vue
<script lang="ts" setup>
import { Slot } from "@/components/ui/slot";
import { CheckIcon } from "lucide-vue-next";
import { cn } from "@/utils/cn";
import { checkboxControl } from "@midoneui/core/styles/checkbox.styles";
import { CheckboxIndicator } from ".";
import type { Api } from "@zag-js/checkbox";
import { inject } from "vue";

const {
  class: className,
  asChild = false,
  ...props
} = defineProps<{
  asChild?: boolean;
  class?: string;
}>();

const api = inject<Api>("checkboxApi");
</script>

<template>
  <Slot
    :class="cn(checkboxControl, className)"
    v-bind="{ ...props, ...$attrs, ...api?.getControlProps() }"
  >
    <slot v-if="asChild" />
    <div v-else>
      <CheckboxIndicator>
        <CheckIcon />
      </CheckboxIndicator>
    </div>
  </Slot>
</template>

// packages/svelte/src/components/ui/checkbox/CheckboxControl.svelte
<script lang="ts">
  import { Check } from "lucide-svelte";
  import { cn } from "@midoneui/core/utils/cn";
  import { checkboxControl, checkboxIndicator } from "@midoneui/core/styles/checkbox.styles";
  import { getContext } from "svelte";
  import type { Snippet } from "svelte";

  let { class: className, children, ...props }: { class?: string; children?: Snippet } & Record<string, any> = $props();
  const getApi = getContext<() => any>("checkboxApi");
  const api = $derived(getApi());
</script>

<div class={cn(checkboxControl, className)} {...api?.getControlProps()} {...props}>
  <div class={cn(checkboxIndicator)} {...api?.getIndicatorProps()}>
    {#if children}
      {@render children()}
    {:else}
      <Check />
    {/if}
  </div>
</div>
