// packages/react/src/components/ui/breadcrumb/index.tsx
import { cn } from "@/utils/cn";
import { ChevronRight, Ellipsis } from "lucide-react";
import {
  breadcrumbList,
  breadcrumbItem,
  breadcrumbLink,
} from "@midoneui/core/styles/breadcrumb.styles";
import {
  MenuRoot,
  MenuTrigger,
  MenuPositioner,
  MenuContent,
  MenuItem,
} from "@/components/ui/menu";
import { Fragment } from "react";

function Breadcrumb({
  className,
  children,
  items,
  ...props
}: React.ComponentProps<"nav"> & {
  items: string[];
}) {
  return (
    <nav
      aria-label="breadcrumb"
      data-slot="breadcrumb"
      {...props}
      className={cn(className)}
    >
      <BreadcrumbList>
        {items.length <= 3 ? (
          items.map((item, key) => (
            <Fragment key={key}>
              <BreadcrumbItem>
                <BreadcrumbLink>{item}</BreadcrumbLink>
              </BreadcrumbItem>
              {key < items.length - 1 && <ChevronRight />}
            </Fragment>
          ))
        ) : (
          <>
            <BreadcrumbItem>
              <BreadcrumbLink>{items[0]}</BreadcrumbLink>
            </BreadcrumbItem>
            <ChevronRight />
            <BreadcrumbItem>
              <MenuRoot>
                <MenuTrigger asChild>
                  <BreadcrumbLink>
                    <Ellipsis />
                  </BreadcrumbLink>
                </MenuTrigger>
                <MenuPositioner>
                  <MenuContent>
                    {items.slice(1, -2).map((item, itemKey) => (
                      <MenuItem value={item} key={itemKey}>
                        {item}
                      </MenuItem>
                    ))}
                  </MenuContent>
                </MenuPositioner>
              </MenuRoot>
            </BreadcrumbItem>
            <ChevronRight />
            {items.slice(-2).map((item, index) => (
              <Fragment key={index}>
                <BreadcrumbItem>
                  <BreadcrumbLink>{item}</BreadcrumbLink>
                </BreadcrumbItem>
                {index < 1 && <ChevronRight />}
              </Fragment>
            ))}
          </>
        )}
      </BreadcrumbList>
    </nav>
  );
}

function BreadcrumbList({
  className,
  children,
  ...props
}: React.ComponentProps<"ol">) {
  return (
    <ol {...props} className={cn(className, breadcrumbList)}>
      {children}
    </ol>
  );
}

function BreadcrumbItem({
  className,
  children,
  ...props
}: React.ComponentProps<"li">) {
  return (
    <li {...props} className={cn(className, breadcrumbItem)}>
      {children}
    </li>
  );
}

function BreadcrumbLink({
  className,
  children,
  ...props
}: React.ComponentProps<"a">) {
  return (
    <a {...props} className={cn(className, breadcrumbLink)}>
      {children}
    </a>
  );
}

export { Breadcrumb, BreadcrumbList, BreadcrumbItem, BreadcrumbLink };

// packages/vue/src/components/ui/breadcrumb/Breadcrumb.vue
<script lang="ts" setup>
import { cn } from "@midoneui/core/utils/cn";
import { ChevronRight, Ellipsis } from "lucide-vue-next";
import {
  breadcrumbList,
  breadcrumbItem,
  breadcrumbLink,
} from "@midoneui/core/styles/breadcrumb.styles";
import {
  MenuRoot,
  MenuTrigger,
  MenuPositioner,
  MenuContent,
  MenuItem,
} from "@/components/ui/menu";
import { BreadcrumbItem, BreadcrumbLink, BreadcrumbList } from ".";

const { class: className, ...props } = defineProps<{
  class?: string;
  items: string[];
}>();
</script>

<template>
  <nav
    aria-label="breadcrumb"
    data-slot="breadcrumb"
    v-bind="{ ...props, ...$attrs }"
    :class="cn(className)"
  >
    <BreadcrumbList>
      <template v-if="items.length <= 3">
        <BreadcrumbItem v-for="(item, key) in items">
          <BreadcrumbLink>{{ item }}</BreadcrumbLink>
        </BreadcrumbItem>
        <ChevronRight v-if="key < items.length - 1" />
      </template>
      <template v-else>
        <BreadcrumbItem>
          <BreadcrumbLink>{{ items[0] }}</BreadcrumbLink>
        </BreadcrumbItem>
        <ChevronRight />
        <BreadcrumbItem>
          <MenuRoot>
            <MenuTrigger asChild>
              <BreadcrumbLink>
                <Ellipsis />
              </BreadcrumbLink>
            </MenuTrigger>
            <MenuPositioner>
              <MenuContent>
                <MenuItem
                  v-for="(item, itemKey) in items.slice(1, -2)"
                  :value="item"
                  :key="itemKey"
                >
                  {{ item }}
                </MenuItem>
              </MenuContent>
            </MenuPositioner>
          </MenuRoot>
        </BreadcrumbItem>
        <ChevronRight />
        <template v-for="(item, index) in items.slice(-2)">
          <BreadcrumbItem>
            <BreadcrumbLink>{{ item }}</BreadcrumbLink>
          </BreadcrumbItem>
          <ChevronRight v-if="index < 1" />
        </template>
      </template>
    </BreadcrumbList>
  </nav>
</template>
