// packages/svelte/src/components/ui/breadcrumb/BreadcrumbLink.svelte
<script lang="ts">
  import { cn } from "@midoneui/core/utils/cn";
  import { breadcrumbLink } from "@midoneui/core/styles/breadcrumb.styles";
  import type { Snippet } from "svelte";

  let { class: className, href = "#", children, ...props }: { class?: string; href?: string; children?: Snippet } & Record<string, any> = $props();
</script>

<a class={cn(breadcrumbLink, className)} {href} {...props}>
  {@render children?.()}
</a>

// packages/vue/src/components/ui/breadcrumb/BreadcrumbLink.vue
<script lang="ts" setup>
import { cn } from "@midoneui/core/utils/cn";
import { breadcrumbLink } from "@midoneui/core/styles/breadcrumb.styles";

const props = defineProps<{
  class?: string;
}>();
</script>

<template>
  <a :class="cn(breadcrumbLink, props.class)" v-bind="props">
    <slot />
  </a>
</template>
