// packages/react/src/pages/breadcrumb.tsx
import { Breadcrumb } from "@/components/ui/breadcrumb";
import {
  Wrapper,
  Title,
  Subtitle,
  Menu,
  Preview,
  SectionTitle,
  SectionContent,
  PreviewCode,
} from "@/components/docs";

function Main() {
  return (
    <>
      <Wrapper>
        <div className="flex flex-col gap-20">
          <div>
            <Title>Breadcrumb</Title>
            <Subtitle>
              A navigation trail that shows users where they are and helps them
              move back through pages easily.
            </Subtitle>
            <Preview>
              {() => ({
                preview: (
                  <>
                    <Breadcrumb
                      items={[
                        "Dashboard",
                        "Users",
                        "Admins",
                        "Settings",
                        "Edit Profile",
                      ]}
                    />
                  </>
                ),
                code: (
                  <PreviewCode>
                    {`
<Breadcrumb
  items={["Dashboard", "Users", "Admins", "Settings", "Edit Profile"]}
/>
                `}
                  </PreviewCode>
                ),
              })}
            </Preview>
          </div>
          <div id="installation">
            <SectionTitle>Installation</SectionTitle>
            <SectionContent>
              Copy and paste the following code into your project.
            </SectionContent>
            <PreviewCode title="components/ui/breadcrumb/index.tsx">
              {`
import { cn } from "@midoneui/core/utils/cn";
import { ChevronRight, Ellipsis } from "lucide-react";
import {
  breadcrumbList,
  breadcrumbItem,
  breadcrumbLink,
} from "@midoneui/core/styles/breadcrumb.styles";
import {
  MenuRoot,
  MenuTrigger,
  MenuPositioner,
  MenuContent,
  MenuItem,
} from "@/components/ui/menu";
import { Fragment } from "react";

function Breadcrumb({
  className,
  children,
  items,
  ...props
}: React.ComponentProps<"nav"> & {
  items: string[];
}) {
  return (
    <nav
      aria-label="breadcrumb"
      data-slot="breadcrumb"
      {...props}
      className={cn(className)}
    >
      <BreadcrumbList>
        {items.length <= 3 ? (
          items.map((item, key) => (
            <Fragment key={key}>
              <BreadcrumbItem>
                <BreadcrumbLink>{item}</BreadcrumbLink>
              </BreadcrumbItem>
              {key < items.length - 1 && <ChevronRight />}
            </Fragment>
          ))
        ) : (
          <>
            <BreadcrumbItem>
              <BreadcrumbLink>{items[0]}</BreadcrumbLink>
            </BreadcrumbItem>
            <ChevronRight />
            <BreadcrumbItem>
              <MenuRoot>
                <MenuTrigger asChild>
                  <BreadcrumbLink>
                    <Ellipsis />
                  </BreadcrumbLink>
                </MenuTrigger>
                <MenuPositioner>
                  <MenuContent>
                    {items.slice(1, -2).map((item, itemKey) => (
                      <MenuItem value={item} key={itemKey}>
                        {item}
                      </MenuItem>
                    ))}
                  </MenuContent>
                </MenuPositioner>
              </MenuRoot>
            </BreadcrumbItem>
            <ChevronRight />
            {items.slice(-2).map((item, index) => (
              <Fragment key={index}>
                <BreadcrumbItem>
                  <BreadcrumbLink>{item}</BreadcrumbLink>
                </BreadcrumbItem>
                {index < 1 && <ChevronRight />}
              </Fragment>
            ))}
          </>
        )}
      </BreadcrumbList>
    </nav>
  );
}

function BreadcrumbList({
  className,
  children,
  ...props
}: React.ComponentProps<"ol">) {
  return (
    <ol {...props} className={cn(className, breadcrumbList)}>
      {children}
    </ol>
  );
}

function BreadcrumbItem({
  className,
  children,
  ...props
}: React.ComponentProps<"li">) {
  return (
    <li {...props} className={cn(className, breadcrumbItem)}>
      {children}
    </li>
  );
}

function BreadcrumbLink({
  className,
  children,
  ...props
}: React.ComponentProps<"a">) {
  return (
    <a {...props} className={cn(className, breadcrumbLink)}>
      {children}
    </a>
  );
}

export { Breadcrumb, BreadcrumbList, BreadcrumbItem, BreadcrumbLink };
              `}
            </PreviewCode>
            <SectionContent>
              Update the import paths to match your project setup.
            </SectionContent>
          </div>
          <div id="usage">
            <SectionTitle>Usage</SectionTitle>
            <PreviewCode>
              {`
import { Breadcrumb } from "@/components/ui/breadcrumb";
              `}
            </PreviewCode>
            <PreviewCode>
              {`
<Breadcrumb
  items={[
    "Dashboard",
    "Users",
    "Admins",
    "Settings",
    "Edit Profile",
  ]}
/>
              `}
            </PreviewCode>
          </div>
        </div>
      </Wrapper>
      <Menu>
        <a className="hover:text-foreground py-1.5" href="#installation">
          Installation
        </a>
        <a className="hover:text-foreground py-1.5" href="#usage">
          Usage
        </a>
      </Menu>
    </>
  );
}

export default Main;

// packages/vue/src/components/ui/breadcrumb/Breadcrumb.vue
<script lang="ts" setup>
import { cn } from "@midoneui/core/utils/cn";
import { ChevronRight, Ellipsis } from "lucide-vue-next";
import {
  breadcrumbList,
  breadcrumbItem,
  breadcrumbLink,
} from "@midoneui/core/styles/breadcrumb.styles";
import {
  MenuRoot,
  MenuTrigger,
  MenuPositioner,
  MenuContent,
  MenuItem,
} from "@/components/ui/menu";
import { BreadcrumbItem, BreadcrumbLink, BreadcrumbList } from ".";

const { class: className, ...props } = defineProps<{
  class?: string;
  items: string[];
}>();
</script>

<template>
  <nav
    aria-label="breadcrumb"
    data-slot="breadcrumb"
    v-bind="{ ...props, ...$attrs }"
    :class="cn(className)"
  >
    <BreadcrumbList>
      <template v-if="items.length <= 3">
        <BreadcrumbItem v-for="(item, key) in items">
          <BreadcrumbLink>{{ item }}</BreadcrumbLink>
        </BreadcrumbItem>
        <ChevronRight v-if="key < items.length - 1" />
      </template>
      <template v-else>
        <BreadcrumbItem>
          <BreadcrumbLink>{{ items[0] }}</BreadcrumbLink>
        </BreadcrumbItem>
        <ChevronRight />
        <BreadcrumbItem>
          <MenuRoot>
            <MenuTrigger asChild>
              <BreadcrumbLink>
                <Ellipsis />
              </BreadcrumbLink>
            </MenuTrigger>
            <MenuPositioner>
              <MenuContent>
                <MenuItem
                  v-for="(item, itemKey) in items.slice(1, -2)"
                  :value="item"
                  :key="itemKey"
                >
                  {{ item }}
                </MenuItem>
              </MenuContent>
            </MenuPositioner>
          </MenuRoot>
        </BreadcrumbItem>
        <ChevronRight />
        <template v-for="(item, index) in items.slice(-2)">
          <BreadcrumbItem>
            <BreadcrumbLink>{{ item }}</BreadcrumbLink>
          </BreadcrumbItem>
          <ChevronRight v-if="index < 1" />
        </template>
      </template>
    </BreadcrumbList>
  </nav>
</template>
