// packages/react/src/components/ui/frame/index.tsx
import { useRef, useEffect } from "react";
import { twMerge } from "tailwind-merge";
import { type Paths, setupSvgRenderer } from "@/utils/frame";

function Frame({
  className,
  paths,
  enableBackdropBlur,
  enableViewBox,
  ...props
}: {
  paths: Paths;
  enableBackdropBlur?: boolean;
  enableViewBox?: boolean;
} & React.ComponentProps<"svg">) {
  const svgRef = useRef<SVGSVGElement | null>(null);

  useEffect(() => {
    if (svgRef.current && svgRef.current.parentElement) {
      const instance = setupSvgRenderer({
        el: svgRef.current,
        paths,
        enableBackdropBlur,
        enableViewBox,
      });

      return () => instance.destroy();
    }
  }, [paths]);

  return (
    <svg
      {...props}
      className={twMerge(["absolute inset-0 size-full", className])}
      xmlns="http://www.w3.org/2000/svg"
      ref={svgRef}
    />
  );
}

export { Frame };

// packages/svelte/src/components/ui/frame/Frame.svelte
<script lang="ts">
  import { cn } from "@midoneui/core/utils/cn";
  import { setupSvgRenderer, type Paths } from "@/utils/frame";
  import { onMount, onDestroy } from "svelte";

  let {
    class: className,
    paths = [],
    enableBackdropBlur = false,
    enableViewBox = false,
    ...props
  }: {
    class?: string;
    paths: Paths;
    enableBackdropBlur?: boolean;
    enableViewBox?: boolean;
  } & Record<string, any> = $props();

  let svgEl: SVGSVGElement;
  let cleanup: (() => void) | null = null;

  onMount(() => {
    const result = setupSvgRenderer({
      el: svgEl,
      paths,
      enableBackdropBlur,
      enableViewBox,
    });
    cleanup = result.destroy;
  });

  onDestroy(() => {
    cleanup?.();
  });
</script>

<svg bind:this={svgEl} class={cn("absolute inset-0 w-full h-full pointer-events-none", className)} {...props}></svg>
